/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Lf2_psw_ub.c
 *
 * Code generation for function 'Lf2_psw_ub'
 *
 */

/* Include files */
#include "Lf2_psw_ub.h"
#include <math.h>

/* Function Definitions */
double Lf2_psw_ub(const double in1[10], double h, double k, double r, double ub)
{
  double b_ct_idx_179_tmp;
  double b_ct_idx_219_tmp;
  double b_ct_idx_239_tmp;
  double b_ct_idx_284_tmp;
  double b_ct_idx_292_tmp;
  double b_ct_idx_83_tmp;
  double b_ct_idx_85_tmp;
  double b_ct_idx_90_tmp;
  double b_t776_tmp;
  double b_t778_tmp;
  double c_t776_tmp;
  double c_t778_tmp;
  double ct_idx_112;
  double ct_idx_115;
  double ct_idx_126;
  double ct_idx_126_tmp;
  double ct_idx_135;
  double ct_idx_135_tmp;
  double ct_idx_136;
  double ct_idx_146;
  double ct_idx_146_tmp;
  double ct_idx_148;
  double ct_idx_149;
  double ct_idx_15;
  double ct_idx_159;
  double ct_idx_159_tmp;
  double ct_idx_160;
  double ct_idx_160_tmp;
  double ct_idx_163;
  double ct_idx_166;
  double ct_idx_175;
  double ct_idx_179;
  double ct_idx_179_tmp;
  double ct_idx_17_tmp;
  double ct_idx_18;
  double ct_idx_186;
  double ct_idx_186_tmp;
  double ct_idx_190;
  double ct_idx_195;
  double ct_idx_195_tmp;
  double ct_idx_206;
  double ct_idx_206_tmp;
  double ct_idx_213;
  double ct_idx_213_tmp;
  double ct_idx_219;
  double ct_idx_219_tmp;
  double ct_idx_220;
  double ct_idx_220_tmp;
  double ct_idx_221;
  double ct_idx_225;
  double ct_idx_23;
  double ct_idx_232;
  double ct_idx_232_tmp;
  double ct_idx_239;
  double ct_idx_239_tmp;
  double ct_idx_242;
  double ct_idx_242_tmp;
  double ct_idx_244;
  double ct_idx_244_tmp;
  double ct_idx_244_tmp_tmp;
  double ct_idx_245;
  double ct_idx_246;
  double ct_idx_246_tmp;
  double ct_idx_25;
  double ct_idx_250;
  double ct_idx_250_tmp;
  double ct_idx_269;
  double ct_idx_273;
  double ct_idx_275;
  double ct_idx_275_tmp;
  double ct_idx_284;
  double ct_idx_284_tmp;
  double ct_idx_289;
  double ct_idx_289_tmp;
  double ct_idx_29;
  double ct_idx_291;
  double ct_idx_292;
  double ct_idx_292_tmp;
  double ct_idx_298;
  double ct_idx_298_tmp;
  double ct_idx_298_tmp_tmp;
  double ct_idx_302;
  double ct_idx_302_tmp;
  double ct_idx_303;
  double ct_idx_303_tmp;
  double ct_idx_305;
  double ct_idx_305_tmp;
  double ct_idx_31;
  double ct_idx_319;
  double ct_idx_319_tmp;
  double ct_idx_323;
  double ct_idx_326;
  double ct_idx_329;
  double ct_idx_329_tmp;
  double ct_idx_347;
  double ct_idx_349;
  double ct_idx_351;
  double ct_idx_353;
  double ct_idx_358;
  double ct_idx_36;
  double ct_idx_360;
  double ct_idx_362;
  double ct_idx_38_tmp;
  double ct_idx_46_tmp;
  double ct_idx_5;
  double ct_idx_50_tmp;
  double ct_idx_62_tmp;
  double ct_idx_8;
  double ct_idx_83_tmp;
  double ct_idx_85_tmp;
  double ct_idx_90_tmp;
  double ct_idx_93_tmp;
  double ct_idx_93_tmp_tmp;
  double ct_idx_96_tmp;
  double ct_idx_96_tmp_tmp;
  double d_t776_tmp;
  double d_t778_tmp;
  double e_t776_tmp;
  double e_t778_tmp;
  double f_t778_tmp;
  double g_t778_tmp;
  double h_t778_tmp;
  double t10;
  double t11;
  double t111;
  double t112;
  double t119;
  double t12;
  double t120;
  double t13;
  double t14;
  double t15;
  double t151;
  double t17;
  double t175;
  double t2;
  double t220;
  double t242;
  double t243;
  double t244;
  double t245;
  double t247;
  double t255;
  double t256;
  double t274;
  double t288;
  double t3;
  double t30;
  double t31;
  double t310;
  double t312;
  double t32;
  double t33;
  double t34;
  double t341;
  double t342;
  double t343;
  double t35;
  double t39;
  double t4;
  double t40;
  double t41;
  double t42;
  double t43;
  double t44;
  double t49;
  double t5;
  double t53;
  double t55;
  double t56;
  double t577;
  double t58;
  double t583;
  double t589;
  double t589_tmp;
  double t598;
  double t598_tmp;
  double t614;
  double t614_tmp;
  double t623;
  double t64;
  double t649;
  double t649_tmp;
  double t68;
  double t684;
  double t684_tmp;
  double t684_tmp_tmp;
  double t69;
  double t7;
  double t707;
  double t708;
  double t714;
  double t715;
  double t716;
  double t717;
  double t720;
  double t721;
  double t722;
  double t732;
  double t733;
  double t743;
  double t749;
  double t754;
  double t758;
  double t766;
  double t767;
  double t773;
  double t776;
  double t776_tmp;
  double t777;
  double t778;
  double t778_tmp;
  double t779;
  double t782;
  double t783;
  double t785;
  double t786;
  double t787;
  double t788;
  double t789;
  double t790;
  double t80;
  double t9;
  (void)r;
  (void)ub;
  /* Lf2_psw_ub */
  /*     Lf2_psw_ub = Lf2_psw_ub(IN1,H,K,R,UB) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     05-Dec-2021 00:44:02 */
  t2 = cos(in1[4]);
  t3 = cos(in1[2]);
  t4 = cos(in1[1]);
  t5 = sin(in1[4]);
  t7 = sin(in1[2]);
  t9 = in1[0] + in1[1];
  t10 = in1[1] + in1[2];
  t11 = t2 * t2;
  t12 = t3 * t3;
  t13 = t4 * t4;
  t14 = cos(t10);
  t15 = in1[2] + t9;
  t17 = sin(t10);
  t31 = in1[3] + -in1[2];
  t34 = t10 + -in1[3];
  t39 = ((in1[5] + in1[7]) + in1[6]) + -in1[8];
  t10 = (in1[3] + in1[4]) - t10;
  t111 = in1[8] * t5 * 0.05952683917824;
  t733 = in1[9] * t5;
  t112 = t733 * 0.05952683917824;
  t30 = t14 * t14;
  t32 = cos(t31);
  t33 = in1[4] + t31;
  t35 = sin(t31);
  t41 = cos(t34);
  t42 = t15 + -in1[3];
  t44 = sin(t34);
  t55 = -in1[9] + t39;
  t56 = cos(t10);
  t58 = sin(t10);
  t40 = cos(t33);
  t43 = sin(t33);
  t49 = t32 * t32;
  t53 = t41 * t41;
  t33 = -in1[4] + t42;
  t64 = t56 * t56;
  t80 = sin(t15) * 36.3549771;
  ct_idx_5 = -(in1[5] * t44 * 0.4005112824388);
  ct_idx_8 = sin(t42) * 8.41871797884;
  ct_idx_15 = in1[9] * t111;
  ct_idx_17_tmp = in1[7] * t5;
  ct_idx_18 = in1[7] * in1[9] * t5 * -0.05952683917824;
  t15 = t43 * 0.11905367835648;
  ct_idx_23 = in1[5] * t43 * 0.05952683917824;
  ct_idx_25 = in1[6] * t43 * 0.05952683917824;
  ct_idx_29 = t58 * 0.13671838506144;
  ct_idx_31 = in1[5] * t58 * 0.06835919253072;
  ct_idx_36 = t733 * t55 * -0.05952683917824;
  ct_idx_38_tmp = t3 * t4;
  t754 = ct_idx_38_tmp * 4.295141349249055E+65;
  t758 = -(t14 * 4.1712330178969239E+65);
  ct_idx_46_tmp = t11 * t14;
  t717 = ct_idx_46_tmp * 1.2979542310402759E+65;
  ct_idx_50_tmp = ct_idx_38_tmp * t11;
  t773 = -(ct_idx_50_tmp * 1.3365105385516521E+65);
  ct_idx_62_tmp = t14 * t49;
  t577 = ct_idx_62_tmp * 6.3517129173536425E+64;
  ct_idx_83_tmp = t3 * t32;
  b_ct_idx_83_tmp = ct_idx_83_tmp * t41;
  t583 = -(b_ct_idx_83_tmp * 6.3517129173536425E+64);
  t31 = t2 * t3;
  ct_idx_85_tmp = t31 * t40;
  b_ct_idx_85_tmp = ct_idx_85_tmp * t41;
  t715 = b_ct_idx_85_tmp * 1.45141210632265E+64;
  ct_idx_90_tmp = t2 * t14;
  t34 = ct_idx_90_tmp * t32;
  b_ct_idx_90_tmp = t34 * t40;
  t716 = b_ct_idx_90_tmp * 2.9028242126453008E+64;
  ct_idx_93_tmp_tmp = t3 * t40;
  ct_idx_93_tmp = ct_idx_93_tmp_tmp * t56;
  t767 = ct_idx_93_tmp * 1.06584903120889E+64;
  ct_idx_96_tmp_tmp = t31 * t32;
  ct_idx_96_tmp = ct_idx_96_tmp_tmp * t56;
  t733 = ct_idx_96_tmp * 1.45141210632265E+64;
  ct_idx_112 = -(t3 * 4.9553499115050528E+100);
  ct_idx_115 = t30 * 1.7105871703254159E+98;
  ct_idx_126_tmp = t3 * t11;
  ct_idx_126 = ct_idx_126_tmp * 1.5419463157121509E+100;
  ct_idx_135_tmp = t4 * t14;
  ct_idx_135 = ct_idx_135_tmp * 4.5595182205090542E+100;
  ct_idx_136 = t53 * 4.478555291354996E+97;
  ct_idx_146_tmp = t11 * t30;
  ct_idx_146 = -(ct_idx_146_tmp * 5.3227998669959494E+97);
  ct_idx_148 = t40 * 1.7213043134374949E+100;
  ct_idx_149 = t49 * 7.81306546529768E+99;
  t255 = t2 * t32;
  ct_idx_159_tmp = t11 * t13;
  ct_idx_159 = -(ct_idx_159_tmp * 1.5126819298048749E+100);
  ct_idx_160_tmp = t2 * t40;
  ct_idx_160 = ct_idx_160_tmp * 4.0006897444853951E+99;
  ct_idx_163 = t64 * 7.5152386145546549E+96;
  ct_idx_166 = -(ct_idx_83_tmp * 6.7479114227517073E+100);
  t789 = t3 * t53;
  ct_idx_175 = t789 * 6.7426769978548048E+99;
  ct_idx_179_tmp = t4 * t11;
  b_ct_idx_179_tmp = ct_idx_179_tmp * t14;
  ct_idx_179 = -(b_ct_idx_179_tmp * 1.4187761605317239E+100);
  ct_idx_186_tmp = t4 * t41;
  ct_idx_186 = -(ct_idx_186_tmp * 1.6109409497405221E+100);
  ct_idx_190 = ct_idx_85_tmp * 1.5419463157121509E+100;
  ct_idx_195_tmp = ct_idx_38_tmp * t41;
  ct_idx_195 = ct_idx_195_tmp * 6.2088905187066541E+100;
  ct_idx_206_tmp = t14 * t41;
  ct_idx_206 = -(ct_idx_206_tmp * 6.0297734184381112E+100);
  t10 = t2 * t4;
  t788 = -(t10 * t41 * 2.156737712244608E+100);
  ct_idx_213_tmp = ct_idx_135_tmp * t32;
  ct_idx_213 = ct_idx_213_tmp * 6.2088905187066541E+100;
  ct_idx_219_tmp = t3 * t14;
  b_ct_idx_219_tmp = ct_idx_219_tmp * t41;
  ct_idx_219 = b_ct_idx_219_tmp * 9.0991388351019223E+99;
  ct_idx_220_tmp = t30 * t32;
  ct_idx_220 = -(ct_idx_220_tmp * 9.0991388351019223E+99);
  ct_idx_221 = t4 * t56 * 1.5838071014798171E+100;
  ct_idx_225 = t30 * t40 * 8.9458776913619762E+99;
  ct_idx_232_tmp = t10 * t56;
  ct_idx_232 = ct_idx_232_tmp * 3.6811159878404221E+99;
  ct_idx_239_tmp = t2 * t30;
  b_ct_idx_239_tmp = ct_idx_239_tmp * t40;
  ct_idx_239 = b_ct_idx_239_tmp * 2.0792186980452931E+99;
  ct_idx_242_tmp = t3 * t64;
  ct_idx_242 = ct_idx_242_tmp * 1.131454749203659E+99;
  ct_idx_244_tmp_tmp = t10 * t14;
  ct_idx_244_tmp = ct_idx_244_tmp_tmp * t40;
  ct_idx_244 = ct_idx_244_tmp * 1.4187761605317239E+100;
  t782 = t31 * t14;
  ct_idx_245 = t782 * t41 * 1.2181983379201291E+100;
  ct_idx_246_tmp = ct_idx_239_tmp * t32;
  ct_idx_246 = -(ct_idx_246_tmp * 1.2181983379201291E+100);
  ct_idx_250_tmp = t255 * t40;
  ct_idx_250 = ct_idx_250_tmp * 3.5706833578206228E+99;
  ct_idx_269 = t40 * t53 * 2.3421552882827978E+99;
  ct_idx_273 = t40 * t40;
  ct_idx_275_tmp = ct_idx_90_tmp * t56;
  ct_idx_275 = ct_idx_275_tmp * 1.3778466142562791E+100;
  ct_idx_284_tmp = t4 * t32;
  b_ct_idx_284_tmp = ct_idx_284_tmp * t41;
  ct_idx_284 = -(b_ct_idx_284_tmp * 1.4377920826275229E+100);
  ct_idx_289_tmp = t32 * t64;
  ct_idx_289 = ct_idx_289_tmp * 3.9975863679454022E+98;
  ct_idx_291 = -(ct_idx_219_tmp * t56 * 8.9458776913619762E+99);
  ct_idx_292_tmp = t31 * t4;
  b_ct_idx_292_tmp = ct_idx_292_tmp * t56;
  ct_idx_292 = -(b_ct_idx_292_tmp * 1.4187761605317239E+100);
  ct_idx_298_tmp_tmp = t14 * t32;
  ct_idx_298_tmp = ct_idx_298_tmp_tmp * t41;
  ct_idx_298 = -(ct_idx_298_tmp * 6.7426769978548048E+99);
  t766 = t2 * t41;
  ct_idx_302_tmp = t766 * t56;
  ct_idx_302 = ct_idx_302_tmp * 2.046764220388046E+97;
  t785 = t10 * t40;
  ct_idx_303_tmp = t785 * t41;
  ct_idx_303 = ct_idx_303_tmp * 3.2854583672995942E+99;
  ct_idx_305_tmp = t782 * t56;
  ct_idx_305 = ct_idx_305_tmp * 2.0792186980452931E+99;
  t256 = t10 * t32;
  ct_idx_319_tmp = t256 * t56;
  ct_idx_319 = ct_idx_319_tmp * 3.2854583672995942E+99;
  t151 = t31 * t41 * t56;
  ct_idx_323 = t151 * 3.0815004239162308E+99;
  t243 = t34 * t56;
  ct_idx_326 = t243 * 1.5407502119581159E+99;
  ct_idx_329_tmp = t32 * t41;
  ct_idx_329 = ct_idx_329_tmp * t56 * 2.3421552882827978E+99;
  ct_idx_347 = in1[5] * t7 * 1.506081824;
  ct_idx_349 = in1[6] * t7 * 1.506081824;
  ct_idx_351 = t17 * 3.459096394;
  ct_idx_353 = in1[5] * t17 * 1.729548197;
  ct_idx_358 = in1[5] * t35 * 0.3487631994496;
  ct_idx_360 = in1[6] * t35 * 0.3487631994496;
  ct_idx_362 = -(t44 * 0.8010225648776);
  t598_tmp = ct_idx_90_tmp * t40 * t41;
  t598 = t598_tmp * 1.5407502119581159E+99;
  t614_tmp = ct_idx_83_tmp * t64;
  t614 = t614_tmp * 1.5407502119581159E+99;
  t790 = t14 * t40 * t56;
  t623 = t790 * 1.131454749203659E+99;
  t649_tmp = t40 * t41 * t56;
  t649 = t649_tmp * 3.9975863679454022E+98;
  t684_tmp_tmp = t32 * t40;
  t749 = t684_tmp_tmp * t41;
  t684_tmp = t749 * t56;
  t684 = t684_tmp * 3.5679135416958708E+98;
  t68 = cos(t33 + 4.71238898038469);
  t69 = sin(t33 + 4.71238898038469);
  t175 = sin(t33) * 1.436905246896;
  t242 = t14 * ct_idx_273;
  t10 = t242 * 1.06584903120889E+64;
  t220 = t15 + t35 * 0.6975263988992;
  t274 = -(t5 * 0.11905367835648) + t15;
  t589_tmp = ct_idx_206_tmp * ct_idx_273;
  t589 = t589_tmp * 1.5407502119581159E+99;
  t707 =
      ((ct_idx_351 + sin(in1[1]) * 7.3760932192376) + ct_idx_362) + ct_idx_29;
  t244 = in1[8] * t220 / 2.0;
  t245 = in1[5] * t220 / 2.0;
  t247 = in1[6] * t220 / 2.0;
  t288 = t7 * 3.012163648 + t220;
  t310 = in1[9] * t274 / 2.0;
  t312 = in1[6] * t274 / 2.0;
  t708 = in1[5] * t707 / 2.0;
  t714 = ct_idx_29 + t274;
  t720 = (ct_idx_29 + ct_idx_362) + t220;
  t776_tmp = ct_idx_126_tmp * t14;
  b_t776_tmp = ct_idx_160_tmp * t41;
  c_t776_tmp = t255 * t56;
  d_t776_tmp = t40 * t56;
  e_t776_tmp = t11 * t12;
  t776 = (((((((((((((-(t4 * 1.664297110460606E+69) +
                      t11 * 4.3795417961373631E+68) +
                     t12 * 8.1859187141425319E+68) +
                    ct_idx_179_tmp * 5.178760014034365E+68) +
                   ct_idx_219_tmp * 9.4005124603600386E+68) +
                  ct_idx_273 * 3.5963751794318893E+67) +
                 -(e_t776_tmp * 2.5471959452723208E+68)) +
                t49 * 2.1431874509412249E+68) +
               -(t776_tmp * 2.9251386507347238E+68)) +
              ct_idx_329_tmp * 2.4611849984110969E+68) +
             -(ct_idx_250_tmp * 9.7946750833659731E+67)) +
            -(b_t776_tmp * 5.6239848196443146E+67)) +
           d_t776_tmp * 4.1299908864194451E+67) +
          -(c_t776_tmp * 5.6239848196443146E+67)) -
         1.407452505368112E+69;
  t777 = (((((((((((((((((t4 * 3.566096229827739E+65 + t754) + t758) +
                        -(ct_idx_179_tmp * 1.1096550276482461E+65)) +
                       -(ct_idx_219_tmp * 2.0142516521020009E+65)) +
                      t717) +
                     t773) +
                    t776_tmp * 6.26770655824882E+64) +
                   t577) +
                  t10) +
                 -(ct_idx_329_tmp * 5.27359116865459E+64)) +
                b_t776_tmp * 1.205053528957428E+64) +
               t583) +
              t715) +
             c_t776_tmp * 1.205053528957428E+64) +
            -(d_t776_tmp * 8.84934837458634E+63)) +
           -t716) +
          -t767) +
         t733;
  t778_tmp = t2 * t12;
  b_t778_tmp = t12 * t41;
  c_t778_tmp = ct_idx_219_tmp * t32;
  t33 = t2 * t56;
  d_t778_tmp = t782 * t40;
  t15 = t41 * ct_idx_273;
  t732 = t778_tmp * t56;
  t743 = t684_tmp_tmp * t56;
  e_t778_tmp = t4 * t40;
  f_t778_tmp = ct_idx_219_tmp * t40;
  g_t778_tmp = t778_tmp * t41;
  h_t778_tmp = t782 * t32;
  t31 = t12 * t56;
  t34 = t49 * t56;
  t778 = ((((((((((((((((((-(t41 * 2.9475088175827819E+68) +
                           ct_idx_284_tmp * 3.0350658774893788E+68) +
                          t256 * 4.0633649782026259E+68) +
                         -(e_t778_tmp * 2.983944812502915E+68)) +
                        -(t766 * 3.94614304458412E+68)) +
                       b_t778_tmp * 1.7143077651235159E+68) +
                      t56 * 2.8978625179985142E+68) +
                     -(t785 * 6.935343922801539E+67)) +
                    t33 * 6.7352697406147925E+67) +
                   f_t778_tmp * 1.6854328601938829E+68) +
                  -(c_t778_tmp * 1.7143077651235159E+68)) +
                 g_t778_tmp * 2.2951258443279339E+68) +
                d_t778_tmp * 3.9173165989055133E+67) +
               -(h_t778_tmp * 2.2951258443279339E+68)) +
              t15 * 7.531584555983923E+66) +
             -(t31 * 1.6854328601938829E+68)) +
            -(t732 * 3.9173165989055133E+67)) +
           -(t34 * 4.412697806454926E+67)) +
          t749 * 4.412697806454926E+67) +
         -(t743 * 7.531584555983923E+66);
  t779 = (((((((((((((((((((t754 + t758) + t717) +
                          -(t41 * 4.716014108132451E+65)) +
                         ct_idx_284_tmp * 4.8561054039830056E+65) +
                        t773) +
                       b_t778_tmp * 2.742892424197626E+65) +
                      -(t785 * 1.1096550276482461E+65)) +
                     t577) +
                    t10) +
                   -(c_t778_tmp * 2.742892424197626E+65)) +
                  t33 * 1.0776431584983669E+65) +
                 d_t778_tmp * 6.26770655824882E+64) +
                t15 * 1.205053528957428E+64) +
               t583) +
              t715) +
             -(t732 * 6.26770655824882E+64)) +
            -t716) +
           -t767) +
          t733) +
         -(t743 * 1.205053528957428E+64);
  t758 = t32 * 1.7507937695762331E+100 + t255 * 2.3439735328698211E+100;
  t786 =
      (((((((((((((((((((((((((((((((((((((t758 + ct_idx_284_tmp *
                                                      1.402799232857399E+100) +
                                          -ct_idx_148) +
                                         -(t41 * 1.362330596779613E+100)) +
                                        -ct_idx_160) +
                                       b_t778_tmp * 7.9234840852483846E+99) +
                                      t256 * 1.8780762936708988E+100) +
                                     -(e_t778_tmp * 1.3791712150019229E+100)) +
                                    -(t766 * 1.8238966332642771E+100)) +
                                   ct_idx_186) +
                                  -(t785 * 3.2054971876116289E+99)) +
                                 t56 * 1.3393842115009421E+100) +
                                f_t778_tmp * 7.7900250562877808E+99) +
                               t33 * 3.113023442192204E+99) +
                              t788) +
                             -(c_t778_tmp * 7.9234840852483846E+99)) +
                            ct_idx_219) +
                           ct_idx_220) +
                          ct_idx_221) +
                         ct_idx_225) +
                        g_t778_tmp * 1.060800952497837E+100) +
                       d_t778_tmp * 1.810573128102865E+99) +
                      ct_idx_232) +
                     ct_idx_239) +
                    ct_idx_245) +
                   ct_idx_246) +
                  t15 * 3.4810779942854331E+98) +
                 -(h_t778_tmp * 1.060800952497837E+100)) +
                -(t31 * 7.7900250562877808E+99)) +
               ct_idx_269) +
              -(t732 * 1.810573128102865E+99)) +
             ct_idx_291) +
            -ct_idx_289) +
           -ct_idx_305) +
          -(t34 * 2.0395369812687571E+99)) +
         t749 * 2.0395369812687571E+99) +
        -(t743 * 3.4810779942854331E+98)) +
       t649) +
      -ct_idx_329;
  t787 =
      ((((((((((((((((((((((((((((((((((((((((t3 * 2.477674955752527E+97 +
                                              ct_idx_38_tmp *
                                                  1.9852027049655879E+97) +
                                             -(t14 * 1.9279326096261111E+97)) +
                                            -(ct_idx_126_tmp *
                                              7.7097315785607553E+96)) +
                                           t32 * 2.8012700313219719E+97) +
                                          ct_idx_46_tmp *
                                              5.9991093211244009E+96) +
                                         -(ct_idx_135_tmp *
                                           2.2797591102545272E+97)) +
                                        -(ct_idx_50_tmp *
                                          6.1773155307487974E+96)) +
                                       b_ct_idx_179_tmp *
                                           7.0938808026586212E+96) +
                                      ct_idx_284_tmp * 2.2444787725718392E+97) +
                                     -(t41 * 2.1797289548473819E+97)) +
                                    -(ct_idx_160_tmp *
                                      6.4011035911766324E+96)) +
                                   -(ct_idx_186_tmp * 2.5775055195848361E+97)) +
                                  b_t778_tmp * 1.267757453639742E+97) +
                                 -(t789 * 3.3713384989274018E+96)) +
                                ct_idx_62_tmp * 2.9357445167432959E+96) +
                               -(t785 * 5.1287955001786067E+96)) +
                              t242 * 4.9263253704346168E+95) +
                             t33 * 4.9808375075075263E+96) +
                            b_ct_idx_219_tmp * 1.4558622136163079E+97) +
                           -(ct_idx_220_tmp * 1.4558622136163079E+97)) +
                          -(c_t778_tmp * 1.267757453639742E+97)) +
                         d_t778_tmp * 2.8969170049645831E+96) +
                        ct_idx_232_tmp * 5.8897855805446754E+96) +
                       b_ct_idx_239_tmp * 3.3267499168724679E+96) +
                      -(ct_idx_242_tmp * 5.6572737460182967E+95)) +
                     t15 * 5.5697247908566932E+95) +
                    -(b_ct_idx_83_tmp * 2.9357445167432959E+96)) +
                   ct_idx_298_tmp * 3.3713384989274018E+96) +
                  -(t732 * 2.8969170049645831E+96)) +
                 b_ct_idx_85_tmp * 6.7083874666785744E+95) +
                -(ct_idx_305_tmp * 3.3267499168724679E+96)) +
               -(ct_idx_289_tmp * 6.3961381887126438E+95)) +
              -(b_ct_idx_90_tmp * 1.3416774933357149E+96)) +
             -(ct_idx_93_tmp * 4.9263253704346168E+95)) +
            ct_idx_96_tmp * 6.7083874666785744E+95) +
           -(t598_tmp * 7.7037510597905785E+95)) +
          t790 * 5.6572737460182967E+95) +
         t151 * 1.5407502119581159E+96) +
        -(t243 * 7.7037510597905785E+95)) +
       -(t743 * 5.5697247908566932E+95)) +
      t649_tmp * 6.3961381887126438E+95;
  t119 = cos(t42 + 4.71238898038469) * 0.4064 + t68 * 0.4667;
  t120 = sin(t42 + 4.71238898038469) * 0.4064 + t69 * 0.4667;
  t341 = in1[5] * t288 / 2.0;
  t342 = in1[7] * t288 / 2.0;
  t343 = in1[6] * t288 / 2.0;
  t717 = in1[9] * t714 / 2.0;
  t721 = in1[8] * t720 / 2.0;
  t722 = in1[5] * t720 / 2.0;
  t783 =
      (((((((((((((((((((((((((((((((((((-(t4 * 2.6371840387918691E+98) +
                                         -(t3 * 3.9642799292040432E+98)) +
                                        t14 * 3.0846921754017772E+98) +
                                       t11 * 1.024176574588261E+98) +
                                      -(ct_idx_38_tmp * 3.17632432794494E+98)) +
                                     ct_idx_115) +
                                    ct_idx_179_tmp * 8.20607280028577E+97) +
                                   ct_idx_126_tmp * 1.233557052569721E+98) +
                                  ct_idx_219_tmp * 1.4895706578535441E+98) +
                                 ct_idx_135_tmp * 3.6476145764072429E+98) +
                                ct_idx_50_tmp * 9.8837048491980743E+97) +
                               ct_idx_136) +
                              -(ct_idx_46_tmp * 9.5985749137990415E+97)) +
                             -(t776_tmp * 4.6350672079433329E+97)) +
                            ct_idx_146) +
                           t789 * 5.3941415982838437E+97) +
                          -(b_ct_idx_179_tmp * 1.1350209284253789E+98)) +
                         ct_idx_163) +
                        -(ct_idx_62_tmp * 4.6971912267892741E+97)) +
                       -(t242 * 7.8821205926953869E+96)) +
                      ct_idx_329_tmp * 3.899903300635676E+97) +
                     ct_idx_242_tmp * 9.0516379936292747E+96) +
                    b_ct_idx_83_tmp * 4.6971912267892741E+97) +
                   d_t776_tmp * 6.5442317826334076E+96) +
                  -(b_t776_tmp * 8.9115596653707073E+96)) +
                 -(ct_idx_298_tmp * 5.3941415982838437E+97)) +
                b_ct_idx_90_tmp * 2.1466839893371438E+97) +
               ct_idx_93_tmp * 7.8821205926953869E+96) +
              -(b_ct_idx_85_tmp * 1.0733419946685719E+97)) +
             -(c_t776_tmp * 8.9115596653707073E+96)) +
            t598_tmp * 1.2326001695664929E+97) +
           -ct_idx_302) +
          -(ct_idx_96_tmp * 1.0733419946685719E+97)) +
         t243 * 1.2326001695664929E+97) +
        -(t790 * 9.0516379936292747E+96)) +
       -(t151 * 2.4652003391329851E+97)) -
      3.2913942895006169E+98;
  t754 = ct_idx_298_tmp_tmp * t40;
  t749 = ct_idx_292_tmp * t41;
  t743 = ct_idx_135_tmp * t40;
  t782 = ct_idx_90_tmp * t41;
  t33 = ct_idx_244_tmp_tmp * t32;
  t15 = t14 * t56;
  b_ct_idx_179_tmp = ct_idx_38_tmp * t56;
  ct_idx_242_tmp = ct_idx_93_tmp_tmp * t53;
  t31 = ct_idx_62_tmp * t56;
  t34 = t754 * t41;
  t10 = b_ct_idx_83_tmp * t56;
  t732 = ct_idx_93_tmp_tmp * t41 * t56;
  t754 *= t56;
  t788 = (((((((((((((((((((((((((((((((((((((((((t758 + -ct_idx_148) +
                                                 ct_idx_83_tmp *
                                                     2.1087223196099079E+100) +
                                                -ct_idx_160) +
                                               ct_idx_96_tmp_tmp *
                                                   2.823170490567743E+100) +
                                              -(ct_idx_93_tmp_tmp *
                                                2.0732041018543329E+100)) +
                                             ct_idx_186) +
                                            ct_idx_206_tmp *
                                                1.88430419326191E+100) +
                                           -(ct_idx_85_tmp *
                                             4.8185822366004722E+99)) +
                                          t788) +
                                         -(ct_idx_195_tmp *
                                           1.9402782870958291E+100)) +
                                        t743 * 1.9075972526767341E+100) +
                                       t782 * 2.5227181142817188E+100) +
                                      ct_idx_219) +
                                     ct_idx_220) +
                                    ct_idx_221) +
                                   ct_idx_225) +
                                  -(ct_idx_213_tmp * 1.9402782870958291E+100)) +
                                 ct_idx_244_tmp * 4.433675501661638E+99) +
                                ct_idx_232) +
                               -(t749 * 2.5976565774822351E+100)) +
                              ct_idx_239) +
                             ct_idx_245) +
                            ct_idx_246) +
                           b_ct_idx_179_tmp * 1.9075972526767341E+100) +
                          -(t33 * 2.5976565774822351E+100)) +
                         b_ct_idx_292_tmp * 4.433675501661638E+99) +
                        -(t15 * 1.852565957254429E+100)) +
                       ct_idx_269) +
                      -(ct_idx_275_tmp * 4.30577066955087E+99)) +
                     ct_idx_291) +
                    ct_idx_242_tmp * 2.8209805279292E+99) +
                   -ct_idx_289) +
                  -ct_idx_305) +
                 -(t589_tmp * 4.8148444123691118E+98)) +
                -(t614_tmp * 4.8148444123691118E+98)) +
               t31 * 2.8209805279292E+99) +
              t649) +
             -ct_idx_329) +
            -(t34 * 2.8209805279292E+99)) +
           t732 * 4.8148444123691118E+98) +
          t754 * 4.8148444123691118E+98) +
         -(t10 * 2.8209805279292E+99);
  ct_idx_219 = e_t778_tmp * t56;
  ct_idx_329 = ct_idx_38_tmp * t14;
  t649 = t30 * ct_idx_273;
  b_ct_idx_83_tmp = t12 * t64;
  ct_idx_148 = f_t778_tmp * t56;
  ct_idx_160 = t2 * t13;
  ct_idx_186 = t41 * t56;
  ct_idx_62_tmp = e_t778_tmp * t41;
  ct_idx_244_tmp_tmp = ct_idx_284_tmp * t56;
  t3 = ct_idx_220_tmp * t40;
  ct_idx_90_tmp = b_t778_tmp * t56;
  ct_idx_135_tmp = ct_idx_292_tmp * t14;
  ct_idx_298_tmp = f_t778_tmp * t41;
  ct_idx_298_tmp_tmp = c_t778_tmp * t56;
  t789 =
      ((((((((((((((((((((((((((((((((((((((((((((((-(t2 *
                                                      3.3538321486300018E+102) +
                                                    t12 *
                                                        1.456992417750339E+102) +
                                                   t13 *
                                                       2.373456356808413E+102) +
                                                  t30 *
                                                      1.301933828265091E+102) +
                                                 t778_tmp *
                                                     1.9506304649607119E+102) +
                                                ct_idx_160 *
                                                    3.1775980577810222E+102) +
                                               ct_idx_239_tmp *
                                                   1.74303706583323E+102) +
                                              ct_idx_273 *
                                                  6.4011035911766322E+100) +
                                             -(ct_idx_83_tmp *
                                               3.3739557113758533E+101)) +
                                            ct_idx_93_tmp_tmp *
                                                3.3171265629669321E+101) +
                                           -(ct_idx_329 *
                                             2.6812167029627671E+102)) +
                                          -(ct_idx_96_tmp_tmp *
                                            4.5170727849083889E+101)) +
                                         ct_idx_195_tmp *
                                             3.1044452593533271E+101) +
                                        -(ct_idx_135_tmp *
                                          3.5896295136773182E+102)) +
                                       ct_idx_85_tmp *
                                           7.7097315785607555E+100) +
                                      t64 * 5.7198741750830758E+100) +
                                     -(ct_idx_206_tmp *
                                       3.0148867092190553E+101)) +
                                    ct_idx_213_tmp * 3.1044452593533271E+101) +
                                   t749 * 4.1562505239715749E+101) +
                                  -(t743 * 3.0521556042827752E+101)) +
                                 -(t782 * 4.0363489828507507E+101)) +
                                t33 * 4.1562505239715749E+101) +
                               t684_tmp_tmp * 3.7503576525917138E+101) +
                              -(t649 * 3.3267499168724678E+100)) +
                             t15 * 2.964105531607087E+101) +
                            ct_idx_275_tmp * 6.8892330712813928E+100) +
                           -(ct_idx_244_tmp * 7.09388080265862E+100)) +
                          -(b_ct_idx_179_tmp * 3.0521556042827752E+101)) +
                         -(b_ct_idx_83_tmp * 3.3267499168724678E+100)) +
                        -(ct_idx_62_tmp * 3.4507803395913723E+101)) +
                       -(b_ct_idx_292_tmp * 7.09388080265862E+100)) +
                      ct_idx_186 * 3.3512305462379441E+101) +
                     t589_tmp * 7.7037510597905788E+99) +
                    -(ct_idx_242_tmp * 4.51356884468672E+100)) +
                   t614_tmp * 7.7037510597905788E+99) +
                  -(ct_idx_244_tmp_tmp * 3.4507803395913723E+101)) +
                 ct_idx_298_tmp * 1.9491173406722068E+101) +
                -(t3 * 1.9491173406722068E+101)) +
               -(ct_idx_219 * 1.1779571161089351E+101)) +
              ct_idx_298_tmp_tmp * 1.9491173406722068E+101) +
             -(ct_idx_90_tmp * 1.9491173406722068E+101)) +
            ct_idx_148 * 6.6534998337449356E+100) +
           -(t31 * 4.51356884468672E+100)) +
          t34 * 4.51356884468672E+100) +
         t10 * 4.51356884468672E+100) +
        -(t732 * 7.7037510597905788E+99)) +
       -(t754 * 7.7037510597905788E+99)) -
      2.5050916094759448E+102;
  b_ct_idx_90_tmp = ct_idx_273 * t53;
  ct_idx_96_tmp = t49 * t64;
  ct_idx_126_tmp = -(t732 * 1.5407502119581159E+99);
  ct_idx_93_tmp = -(t754 * 1.5407502119581159E+99);
  t790 =
      ((((((((((((((((((((((((((((((((((((((((((((((((ct_idx_112 +
                                                      t11 *
                                                          3.193154826116699E+100) +
                                                     t13 *
                                                         9.7226060215097672E+100) +
                                                    ct_idx_126) +
                                                   ct_idx_135) +
                                                  -(t32 *
                                                    5.6025400626439448E+100)) +
                                                 t49 * 1.562613093059536E+100) +
                                                ct_idx_273 *
                                                    2.622142519762599E+99) +
                                               -(ct_idx_159_tmp *
                                                 3.02536385960975E+100)) +
                                              t53 * 1.3963139557619591E+100) +
                                             ct_idx_166) +
                                            ct_idx_186_tmp *
                                                5.1550110391696713E+100) +
                                           ct_idx_160_tmp *
                                               1.2802207182353259E+100) +
                                          ct_idx_175) +
                                         ct_idx_179) +
                                        ct_idx_190) +
                                       ct_idx_195) +
                                      t64 * 2.3430842929727389E+99) +
                                     ct_idx_220_tmp * 2.9117244272326148E+100) +
                                    ct_idx_206) +
                                   ct_idx_213) +
                                  -(b_ct_idx_219_tmp *
                                    2.9117244272326148E+100)) +
                                 ct_idx_242) +
                                -(b_ct_idx_239_tmp * 6.6534998337449362E+99)) +
                               -ct_idx_244) +
                              -(ct_idx_232_tmp * 1.1779571161089351E+100)) +
                             -(ct_idx_250_tmp * 7.1413667156412446E+99)) +
                            ct_idx_275) +
                           -(b_ct_idx_284_tmp * 2.875584165255047E+100)) +
                          -(b_ct_idx_90_tmp * 3.5679135416958708E+98)) +
                         ct_idx_292) +
                        ct_idx_298) +
                       ct_idx_303_tmp * 6.5709167345991884E+99) +
                      ct_idx_305_tmp * 6.6534998337449362E+99) +
                     ct_idx_289_tmp * 1.279227637742529E+99) +
                    t589) +
                   t598) +
                  ct_idx_319_tmp * 6.5709167345991884E+99) +
                 -(ct_idx_96_tmp * 3.5679135416958708E+98)) +
                t614) +
               -(ct_idx_219 * 4.8253733072899684E+99)) +
              -(ct_idx_302_tmp * 6.3813557255813289E+99)) +
             ct_idx_326) +
            -t623) +
           -ct_idx_323) +
          -(t649_tmp * 1.279227637742529E+99)) +
         ct_idx_126_tmp) +
        ct_idx_93_tmp) +
       t684_tmp * 7.1358270833917428E+98) -
      1.0261835528113919E+101;
  t42 = sin(t9 + 1.5707963267948966) * 0.4064 + t120;
  t151 = cos(t9 + 1.5707963267948966) * 0.4064 + t119;
  ct_idx_46_tmp = t12 * t53;
  b_ct_idx_85_tmp = t30 * t49;
  t598_tmp = c_t778_tmp * t41;
  t785 =
      1.0 /
      ((((((((((((((((((((((((((((((((-(t11 * 3.9928605388461837E+110) +
                                      -(t13 * 1.215757206650896E+111)) +
                                     -(t12 * 7.46316243327777E+110)) +
                                    -(t30 * 6.66890473783269E+110)) +
                                   ct_idx_159_tmp * 3.7830473711723741E+110) +
                                  e_t776_tmp * 2.3222973196778359E+110) +
                                 ct_idx_329 * 1.373401503621102E+111) +
                                -(t49 * 1.953959797292265E+110)) +
                               ct_idx_146_tmp * 2.07514974199132E+110) +
                              -(ct_idx_273 * 3.2788417613697459E+109)) +
                             -(t53 * 1.74601207814982E+110)) +
                            -(ct_idx_50_tmp * t14 * 4.273585975402672E+110)) +
                           -(t64 * 2.9298951419711852E+109)) +
                          ct_idx_46_tmp * 1.015502327157201E+110) +
                         t649 * 1.70406343245411E+109) +
                        b_ct_idx_85_tmp * 1.015502327157201E+110) +
                       b_ct_idx_83_tmp * 1.70406343245411E+109) +
                      ct_idx_250_tmp * 8.9298774738683466E+109) +
                     b_ct_idx_284_tmp * 3.5957562864376437E+110) +
                    b_ct_idx_90_tmp * 4.4614752376343817E+108) +
                   ct_idx_96_tmp * 4.4614752376343817E+108) +
                  ct_idx_219 * 6.0338579596251836E+109) +
                 -(ct_idx_303_tmp * 8.2165618525715213E+109)) +
                -(t598_tmp * 2.0310046543144019E+110)) +
               ct_idx_302_tmp * 7.9795264710044618E+109) +
              d_t778_tmp * t41 * 4.6409917791085313E+109) +
             -(ct_idx_246_tmp * t40 * 4.6409917791085313E+109)) +
            -(ct_idx_319_tmp * 8.2165618525715213E+109)) +
           -(g_t778_tmp * t56 * 4.6409917791085313E+109)) +
          -(ct_idx_148 * 3.40812686490822E+109)) +
         h_t778_tmp * t56 * 4.6409917791085313E+109) +
        -(t684_tmp * 8.9229504752687635E+108)) +
       1.283184824024515E+111);
  t242 = cos(in1[0] + 1.5707963267948966) * 0.4667 + t151;
  t243 = sin(in1[0] + 1.5707963267948966) * 0.4667 + t42;
  t733 = (t244 + t310) + -t342;
  t15 = ((in1[6] * t707 / 2.0 + -t717) + -t721) +
        in1[7] * (((ct_idx_351 + ct_idx_362) + ct_idx_29) + t288) / 2.0;
  t255 = -k + t243;
  t256 = -h + t242;
  t766 = (((((ct_idx_8 + ct_idx_15) + ct_idx_18) + ct_idx_36) + t175) +
          in1[6] * ((-t112 + t245) + t247)) +
         in1[5] * ((-t112 + t247) + t722);
  t10 = t111 + -(ct_idx_17_tmp * 0.05952683917824);
  t767 = (((t39 * t111 + ct_idx_17_tmp * t39 * -0.05952683917824) + t175) +
          in1[6] * ((t10 + in1[5] * t274 / 2.0) + t312)) +
         in1[5] * ((t10 + t312) + in1[5] * t714 / 2.0);
  t773 =
      ((((((ct_idx_8 + -t80) + ct_idx_15) + ct_idx_18) + ct_idx_36) + t175) +
       in1[6] * ((-t112 + t341) + t343)) +
      in1[5] * (((((((((ct_idx_347 + ct_idx_349) + ct_idx_353) + ct_idx_358) +
                     ct_idx_360) +
                    ct_idx_5) +
                   -t112) +
                  ct_idx_23) +
                 ct_idx_25) +
                ct_idx_31);
  t577 = t68 * t256 * 0.9334;
  t583 = t69 * t255 * 0.9334;
  t10 = t119 * t256 * 2.0;
  t33 = t120 * t255 * 2.0;
  t715 = t151 * t256 * 2.0;
  t716 = t42 * t255 * 2.0;
  t34 = (t80 + -ct_idx_8) + sin(t9) * 77.52247105284;
  t31 = in1[9] * t55;
  t782 =
      ((((((t34 + sin(in1[0]) * 97.255892295144) + -t175) +
          -(t31 * ((-(t5 * 4064.0) + t43 * 4064.0) + t58 * 4667.0) *
            1.464735216E-5)) +
         in1[5] * t15) +
        in1[6] * (t708 + t15)) +
       -in1[8] *
           ((((-t717 + t722) + in1[7] * t720 / 2.0) + in1[6] * t720 / 2.0) +
            -t721)) +
      in1[7] * ((((((((((((((((((((((((ct_idx_347 + in1[7] * t7 * 1.506081824) +
                                      ct_idx_349) +
                                     ct_idx_353) +
                                    in1[7] * t17 * 1.729548197) +
                                   in1[6] * t17 * 1.729548197) +
                                  ct_idx_358) +
                                 in1[7] * t35 * 0.3487631994496) +
                                ct_idx_360) +
                               -(in1[8] * t35 * 0.3487631994496)) +
                              in1[8] * t44 * 0.4005112824388) +
                             ct_idx_5) +
                            -(in1[7] * t44 * 0.4005112824388)) +
                           -(in1[6] * t44 * 0.4005112824388)) +
                          t112) +
                         ct_idx_23) +
                        in1[7] * t43 * 0.05952683917824) +
                       ct_idx_25) +
                      -(in1[8] * t43 * 0.05952683917824)) +
                     -(in1[9] * t43 * 0.05952683917824)) +
                    ct_idx_31) +
                   in1[7] * t58 * 0.06835919253072) +
                  in1[6] * t58 * 0.06835919253072) +
                 -(in1[8] * t58 * 0.06835919253072)) +
                -(in1[9] * t58 * 0.06835919253072));
  t732 = t120 * t256 * 2.0 + -(t119 * t255 * 2.0);
  t743 = ((t69 * t120 * 0.9334 + t68 * t119 * 0.9334) + -t577) + -t583;
  t749 = ((t68 * t151 * 0.9334 + t69 * t42 * 0.9334) + -t577) + -t583;
  t754 = ((t69 * t243 * 0.9334 + t68 * t242 * 0.9334) + -t577) + -t583;
  t758 = ((t119 * t151 * 2.0 + t120 * t42 * 2.0) + -t10) + -t33;
  t717 = ((t119 * t242 * 2.0 + t120 * t243 * 2.0) + -t10) + -t33;
  t10 = ((t119 * t119 * 2.0 + t120 * t120 * 2.0) + -t10) + -t33;
  ct_idx_242_tmp =
      (((-in1[8] * t10 + in1[6] * t758) + -in1[9] * t743) + in1[7] * t10) +
      in1[5] * t717;
  t34 = (((((t34 + -t175) - in1[6] * t733) - in1[5] * (t708 + t733)) +
          in1[7] * ((((-t244 + -t310) + t341) + t342) + t343)) +
         -in1[8] * ((((t245 + in1[7] * t220 / 2.0) + t247) + -t244) + -t310)) +
        t31 * (t5 - t43) * 0.05952683917824;
  t33 = t766 * t785;
  t15 = t767 * t785;
  t733 = t773 * t785;
  b_ct_idx_179_tmp = ((t151 * t242 * 2.0 + t42 * t243 * 2.0) - t715) - t716;
  t31 = -(b_ct_idx_90_tmp * 1.783956770847936E+98);
  t10 = -(ct_idx_96_tmp * 1.783956770847936E+98);
  return (((((((in1[5] *
                    ((((in1[5] * (((t242 * t256 * 2.0 + t243 * t255 * 2.0) -
                                   t242 * t242 * 2.0) -
                                  t243 * t243 * 2.0) +
                        in1[9] * t754) -
                       in1[6] * b_ct_idx_179_tmp) +
                      in1[8] * t717) -
                     in1[7] * t717) +
                in1[8] * ct_idx_242_tmp) -
               in1[7] * ct_idx_242_tmp) +
              -(t732 *
                ((((t33 *
                        (((((((((((((t11 * 1.59657741305835E+100 +
                                     t12 * 1.4569924177503392E+101) +
                                    t13 * 2.8595866578839019E+101) +
                                   t30 * 1.301933828265091E+101) +
                                  ct_idx_273 * 7.7121748510579323E+99) +
                                 t53 * 6.9815697788097973E+99) +
                                (((((((((((((((((((((t64 *
                                                         6.8914163215694463E+99 +
                                                     ct_idx_149) +
                                                    ct_idx_159) +
                                                   ct_idx_166) +
                                                  ct_idx_190) +
                                                 ct_idx_195) +
                                                ct_idx_206) +
                                               ct_idx_213) +
                                              -ct_idx_244) +
                                             -ct_idx_250) +
                                            ct_idx_275) +
                                           ct_idx_284) +
                                          t31) +
                                         ct_idx_292) +
                                        ct_idx_303) +
                                       t589) +
                                      ct_idx_319) +
                                     t10) +
                                    t614) +
                                   ct_idx_126_tmp) +
                                  ct_idx_93_tmp) +
                                 t684)) +
                               b_ct_idx_83_tmp * -3.3267499168724681E+99) +
                              t649 * -3.3267499168724681E+99) +
                             ct_idx_329 * -2.681216702962767E+101) +
                            ct_idx_302_tmp * -3.190677862790664E+99) +
                           ct_idx_219 * -1.4192257814734329E+100) +
                          ct_idx_148 * 6.6534998337449362E+99) +
                         -3.018183385881641E+101) *
                        -2.0E+10 +
                    t15 * t789 * 2.0E+9) +
                   t779 * t782 * t785 * 9.2439458613517916E+44) +
                  t733 * t790 * 1.0E+10) -
                 t785 * t787 * t34 * 2.0E+13))) +
             -((t42 * t256 * 2.0 - t151 * t255 * 2.0) *
               ((((t785 * t34 *
                       (((((((((((((t4 * -5.2743680775837369E+98 +
                                    t11 * 1.7181426729130289E+98) +
                                   t12 * 1.2971105964252839E+98) +
                                  ((t49 * 3.3960160732340671E+97 +
                                    ct_idx_273 * 5.6986839435659248E+96) +
                                   ct_idx_115)) +
                                 ((((ct_idx_136 + ct_idx_146) + ct_idx_163) +
                                   -ct_idx_302) +
                                  ct_idx_179_tmp * 1.6412145600571541E+98)) +
                                ct_idx_219_tmp * 2.9791413157070881E+98) +
                               e_t776_tmp * -4.036193086154212E+97) +
                              ct_idx_329_tmp * 7.7998066012713534E+97) +
                             d_t776_tmp * 1.3088463565266821E+97) +
                            t776_tmp * -9.2701344158866658E+97) +
                           ct_idx_250_tmp * -1.55202821855867E+97) +
                          b_t776_tmp * -1.7823119330741418E+97) +
                         c_t776_tmp * -1.7823119330741418E+97) +
                        -5.5215918060288816E+98) *
                       1.25E+12 +
                   t33 * t787 * 2.0E+13) -
                  t15 * t786 * 3.2E+10) +
                 t773 * t783 * t785 * 1.25E+12) -
                t776 * t782 * t785 * 1.9807040628566081E+41))) +
            in1[9] * ((((in1[7] * t743 + in1[5] * t754) + in1[6] * t749) +
                       -in1[8] * t743) +
                      in1[9] * (((t577 + t583) - t68 * t68 * 0.43561778) -
                                t69 * t69 * 0.43561778))) +
           (t242 * t255 * 2.0 - t243 * t256 * 2.0) *
               ((((t782 * t785 *
                       ((((t11 * 2.1897708980686811E+68 +
                           t12 * 4.0929593570712659E+68) +
                          (t49 * 1.071593725470613E+68 +
                           ct_idx_273 * 1.798187589715944E+67)) +
                         (e_t776_tmp * -1.27359797263616E+68 -
                          ct_idx_250_tmp * 4.8973375416829859E+67)) +
                        -7.0372625268405592E+68) *
                       3.9614081257132169E+41 -
                   t766 * t779 * t785 * 9.2439458613517916E+44) +
                  t767 * t778 * t785 * 1.479031337816287E+42) +
                 t773 * t777 * t785 * 9.2439458613517916E+44) +
                t776 * t785 * t34 * -1.9807040628566081E+41)) +
          ((t68 * t255 * 0.9334 - t69 * t256 * 0.9334) *
               ((((t33 * t789 * 2.0E+9 -
                   t778 * t782 * t785 * 1.479031337816287E+42) +
                  t733 * t788 * 3.2E+10) +
                 t785 * t786 * t34 * 3.2E+10) +
                t15 *
                    (((((((((((((((((((((((((((((t2 * -4.1922901857875019E+105 +
                                                 t12 *
                                                     6.1560105058131068E+105) +
                                                t13 * 1.002820748385332E+106) +
                                               t30 * 5.50086481372941E+105) +
                                              t49 * 1.3733161713845791E+105) +
                                             ct_idx_273 *
                                                 4.0006897444853948E+103) +
                                            t53 * 1.2271627214023409E+105) +
                                           t64 * 3.574921359426923E+103) +
                                          t778_tmp * 2.43828808120089E+105) +
                                         ct_idx_160 * 3.9719975722262778E+105) +
                                        ct_idx_239_tmp *
                                            2.1787963322915381E+105) +
                                       ct_idx_46_tmp *
                                           -7.1373309210161707E+104) +
                                      t684_tmp_tmp * 4.687947065739642E+104) +
                                     b_ct_idx_83_tmp *
                                         -2.0792186980452929E+103) +
                                    b_ct_idx_85_tmp *
                                        -7.1373309210161707E+104) +
                                   t649 * -2.0792186980452929E+103) +
                                  ct_idx_186 * 4.1890381827974309E+104) +
                                 ct_idx_329 * -1.1328540897478209E+106) +
                                b_ct_idx_284_tmp * -2.5272322712911758E+105) +
                               ct_idx_62_tmp * -4.3134754244892159E+104) +
                              ct_idx_244_tmp_tmp * -4.3134754244892159E+104) +
                             ct_idx_219 * -7.3622319756808429E+103) +
                            t3 * -2.436396675840258E+104) +
                           ct_idx_90_tmp * -2.436396675840258E+104) +
                          ct_idx_135_tmp * -4.487036892096648E+105) +
                         t598_tmp * 1.4274661842032339E+105) +
                        ct_idx_298_tmp * 2.436396675840258E+104) +
                       ct_idx_298_tmp_tmp * 2.436396675840258E+104) +
                      ct_idx_148 * 4.158437396090585E+103) +
                     -1.0584386080587479E+106) *
                    -3.2E+6) +
           in1[6] * ((((in1[9] * t749 + in1[8] * t758) - in1[7] * t758) +
                      in1[6] * (((t715 + t716) - t42 * t42 * 2.0) -
                                t151 * t151 * 2.0)) -
                     in1[5] * b_ct_idx_179_tmp))) +
         t732 * ((((t733 *
                        (((((((((t11 * 2.2366877721760131E+100 +
                                 t13 * 4.8613030107548844E+100) +
                                t30 * 1.069116981453385E+100) +
                               ct_idx_273 * 1.3110712598813E+99) +
                              t53 * 9.78066683590667E+99) +
                             ((((((((((((((((((((t64 * 1.641244559896035E+99 +
                                                 ct_idx_112) +
                                                ct_idx_126) +
                                               ct_idx_135) +
                                              ct_idx_149) +
                                             ct_idx_159) +
                                            ct_idx_175) +
                                           ct_idx_179) +
                                          ct_idx_242) +
                                         -ct_idx_250) +
                                        ct_idx_284) +
                                       t31) +
                                      ct_idx_298) +
                                     ct_idx_303) +
                                    t598) +
                                   ct_idx_319) +
                                  t10) +
                                 ct_idx_326) +
                                -t623) +
                               -ct_idx_323) +
                              t684)) +
                            ct_idx_146_tmp * -3.3267499168724681E+99) +
                           ct_idx_302_tmp * -4.4699055005331928E+99) +
                          ct_idx_219 * -2.4126866536449842E+99) +
                         -7.1880391949948467E+100) *
                        2.0E+10 -
                    t15 * t788 * 3.2E+10) -
                   t33 * t790 * 1.0E+10) +
                  t777 * t782 * t785 * 9.2439458613517916E+44) +
                 t783 * t785 * t34 * 1.25E+12);
}

/* End of code generation (Lf2_psw_ub.c) */
