/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * LgLf_psw_ub.c
 *
 * Code generation for function 'LgLf_psw_ub'
 *
 */

/* Include files */
#include "LgLf_psw_ub.h"
#include <math.h>

/* Function Definitions */
void LgLf_psw_ub(const double in1[10], double h, double k, double r, double ub,
                 double b_LgLf_psw_ub[4])
{
  double b_ct_idx_50_tmp;
  double b_ct_idx_50_tmp_tmp;
  double b_ct_idx_51_tmp;
  double b_ct_idx_52_tmp;
  double b_ct_idx_55_tmp;
  double b_ct_idx_56_tmp;
  double b_t206_tmp;
  double b_t236_tmp;
  double b_t254_tmp;
  double b_t389_tmp;
  double b_t413_tmp;
  double c_ct_idx_50_tmp;
  double c_ct_idx_50_tmp_tmp;
  double c_ct_idx_51_tmp;
  double c_ct_idx_52_tmp;
  double c_ct_idx_55_tmp;
  double ct_idx_24;
  double ct_idx_24_tmp;
  double ct_idx_28;
  double ct_idx_28_tmp;
  double ct_idx_28_tmp_tmp;
  double ct_idx_29;
  double ct_idx_29_tmp;
  double ct_idx_33;
  double ct_idx_33_tmp;
  double ct_idx_33_tmp_tmp;
  double ct_idx_39;
  double ct_idx_39_tmp;
  double ct_idx_39_tmp_tmp;
  double ct_idx_40;
  double ct_idx_40_tmp;
  double ct_idx_49;
  double ct_idx_49_tmp;
  double ct_idx_49_tmp_tmp;
  double ct_idx_49_tmp_tmp_tmp;
  double ct_idx_5;
  double ct_idx_50;
  double ct_idx_50_tmp;
  double ct_idx_50_tmp_tmp;
  double ct_idx_51;
  double ct_idx_51_tmp;
  double ct_idx_51_tmp_tmp;
  double ct_idx_52;
  double ct_idx_52_tmp;
  double ct_idx_54;
  double ct_idx_55_tmp;
  double ct_idx_56_tmp;
  double ct_idx_6;
  double ct_idx_6_tmp;
  double d_ct_idx_50_tmp;
  double d_ct_idx_51_tmp;
  double d_ct_idx_52_tmp;
  double d_ct_idx_55_tmp;
  double e_ct_idx_50_tmp;
  double e_ct_idx_51_tmp;
  double e_ct_idx_52_tmp;
  double e_ct_idx_55_tmp;
  double f_ct_idx_50_tmp;
  double f_ct_idx_51_tmp;
  double f_ct_idx_52_tmp;
  double g_ct_idx_50_tmp;
  double g_ct_idx_51_tmp;
  double g_ct_idx_52_tmp;
  double h_ct_idx_50_tmp;
  double h_ct_idx_51_tmp;
  double i_ct_idx_50_tmp;
  double i_ct_idx_51_tmp;
  double j_ct_idx_50_tmp;
  double j_ct_idx_51_tmp;
  double k_ct_idx_50_tmp;
  double k_ct_idx_51_tmp;
  double l_ct_idx_50_tmp;
  double l_ct_idx_51_tmp;
  double m_ct_idx_50_tmp;
  double m_ct_idx_51_tmp;
  double n_ct_idx_50_tmp;
  double n_ct_idx_51_tmp;
  double o_ct_idx_50_tmp;
  double o_ct_idx_51_tmp;
  double p_ct_idx_50_tmp;
  double q_ct_idx_50_tmp;
  double r_ct_idx_50_tmp;
  double s_ct_idx_50_tmp;
  double t108;
  double t108_tmp;
  double t116;
  double t116_tmp;
  double t118;
  double t136;
  double t145_tmp;
  double t153;
  double t153_tmp;
  double t159;
  double t171;
  double t171_tmp;
  double t18;
  double t180;
  double t19;
  double t199;
  double t199_tmp;
  double t2;
  double t20;
  double t204;
  double t204_tmp;
  double t206;
  double t206_tmp;
  double t217;
  double t217_tmp;
  double t22;
  double t231;
  double t231_tmp;
  double t236;
  double t236_tmp;
  double t24;
  double t240;
  double t247;
  double t25;
  double t254;
  double t254_tmp;
  double t255;
  double t255_tmp;
  double t264;
  double t264_tmp;
  double t27;
  double t270;
  double t270_tmp;
  double t275;
  double t275_tmp;
  double t275_tmp_tmp;
  double t3;
  double t30;
  double t312;
  double t32;
  double t323;
  double t323_tmp;
  double t325;
  double t33;
  double t344;
  double t344_tmp;
  double t35;
  double t364;
  double t364_tmp;
  double t38;
  double t389;
  double t389_tmp;
  double t397;
  double t397_tmp;
  double t4;
  double t41;
  double t413;
  double t413_tmp;
  double t42;
  double t430;
  double t430_tmp;
  double t443;
  double t443_tmp;
  double t446;
  double t446_tmp;
  double t5;
  double t503;
  double t504;
  double t51;
  double t52;
  double t53;
  double t55;
  double t6;
  double t7;
  double t72;
  double t74;
  double t8;
  double t9;
  double t96;
  double t_ct_idx_50_tmp;
  double u_ct_idx_50_tmp;
  double v_ct_idx_50_tmp;
  (void)r;
  (void)ub;
  /* LgLf_psw_ub */
  /*     LgLf_psw_ub = LgLf_psw_ub(IN1,H,K,R,UB) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     05-Dec-2021 00:44:07 */
  t2 = cos(in1[4]);
  t3 = cos(in1[2]);
  t4 = cos(in1[1]);
  t5 = in1[1] + in1[2];
  t6 = t2 * t2;
  t7 = t3 * t3;
  t8 = t4 * t4;
  t9 = cos(t5);
  t19 = in1[3] + -in1[2];
  t22 = t5 + -in1[3];
  t18 = t9 * t9;
  t20 = cos(t19);
  t25 = cos(t22);
  t27 = in1[1] + (in1[0] + 1.5707963267948966);
  t35 = cos((in1[3] + in1[4]) - t5);
  t22 += in1[0] + 4.71238898038469;
  t108_tmp = t3 * t6;
  t108 = t108_tmp * 1.5419463157121509E+100;
  t116_tmp = t4 * t9;
  t116 = t116_tmp * 4.5595182205090542E+100;
  t24 = cos(in1[4] + t19);
  t30 = t20 * t20;
  t33 = t25 * t25;
  t38 = t35 * t35;
  t5 = -in1[4] + t22;
  t96 = t18 * 1.7105871703254159E+98;
  t145_tmp = t2 * t20;
  t171_tmp = t4 * t25;
  t171 = t171_tmp * 1.6109409497405221E+100;
  t204_tmp = t2 * t4;
  t204 = t204_tmp * t25 * 2.156737712244608E+100;
  t206_tmp = t3 * t4;
  b_t206_tmp = t206_tmp * t25;
  t206 = b_t206_tmp * 6.2088905187066541E+100;
  t217_tmp = t18 * t20;
  t217 = t217_tmp * 9.0991388351019223E+99;
  t231_tmp = t116_tmp * t20;
  t231 = t231_tmp * 6.2088905187066541E+100;
  t236_tmp = t3 * t9;
  b_t236_tmp = t236_tmp * t25;
  t236 = b_t236_tmp * 9.0991388351019223E+99;
  t240 = t4 * t35 * 1.5838071014798171E+100;
  t254_tmp = t2 * t18;
  b_t254_tmp = t254_tmp * t20;
  t254 = b_t254_tmp * 1.2181983379201291E+100;
  t255_tmp = t204_tmp * t35;
  t255 = t255_tmp * 3.6811159878404221E+99;
  t275_tmp_tmp = t2 * t3;
  t275_tmp = t275_tmp_tmp * t9;
  t275 = t275_tmp * t25 * 1.2181983379201291E+100;
  t504 = t2 * t9;
  t323_tmp = t504 * t35;
  t323 = t323_tmp * 1.3778466142562791E+100;
  t325 = t236_tmp * t35 * 8.9458776913619762E+99;
  t364_tmp = t275_tmp * t35;
  t364 = t364_tmp * 2.0792186980452931E+99;
  t19 = t504 * t20;
  t430_tmp = t19 * t35;
  t430 = t430_tmp * 1.5407502119581159E+99;
  t443_tmp = t20 * t25;
  t443 = t443_tmp * t35 * 2.3421552882827978E+99;
  t32 = t24 * t24;
  t41 = cos(t5);
  t42 = sin(t5);
  t118 = t33 * 4.478555291354996E+97;
  t136 = t24 * 1.7213043134374949E+100;
  t153_tmp = t2 * t24;
  t153 = t153_tmp * 4.0006897444853951E+99;
  t159 = t38 * 7.5152386145546549E+96;
  t5 = t3 * t33;
  t180 = t5 * 6.7426769978548048E+99;
  t199_tmp = t275_tmp_tmp * t24;
  t199 = t199_tmp * 1.5419463157121509E+100;
  t247 = t18 * t24 * 8.9458776913619762E+99;
  t264_tmp = t254_tmp * t24;
  t264 = t264_tmp * 2.0792186980452931E+99;
  t270_tmp = t3 * t38;
  t270 = t270_tmp * 1.131454749203659E+99;
  t312 = t24 * t33 * 2.3421552882827978E+99;
  t344_tmp = t20 * t38;
  t344 = t344_tmp * 3.9975863679454022E+98;
  t397_tmp = t504 * t24 * t25;
  t397 = t397_tmp * 1.5407502119581159E+99;
  t413_tmp = t3 * t20;
  b_t413_tmp = t413_tmp * t38;
  t413 = b_t413_tmp * 1.5407502119581159E+99;
  t446_tmp = t24 * t25 * t35;
  t446 = t446_tmp * 3.9975863679454022E+98;
  t389_tmp = t9 * t25;
  b_t389_tmp = t389_tmp * t32;
  t389 = b_t389_tmp * 1.5407502119581159E+99;
  t51 = cos(t22) * 0.4064 + t41 * 0.4667;
  t52 = sin(t22) * 0.4064 + t42 * 0.4667;
  t53 = sin(t27) * 0.4064 + t52;
  t55 = cos(t27) * 0.4064 + t51;
  t72 = sin(in1[0] + 1.5707963267948966) * 0.4667 + t53;
  ct_idx_5 = t30 * 7.81306546529768E+99;
  ct_idx_6_tmp = t6 * t8;
  ct_idx_6 = -(ct_idx_6_tmp * 1.5126819298048749E+100);
  ct_idx_24_tmp = t145_tmp * t24;
  ct_idx_24 = -(ct_idx_24_tmp * 3.5706833578206228E+99);
  ct_idx_28_tmp_tmp = t4 * t20;
  ct_idx_28_tmp = ct_idx_28_tmp_tmp * t25;
  ct_idx_28 = -(ct_idx_28_tmp * 1.4377920826275229E+100);
  ct_idx_29_tmp = t32 * t33;
  ct_idx_29 = -(ct_idx_29_tmp * 1.783956770847936E+98);
  ct_idx_33_tmp_tmp = t204_tmp * t24;
  ct_idx_33_tmp = ct_idx_33_tmp_tmp * t25;
  ct_idx_33 = ct_idx_33_tmp * 3.2854583672995942E+99;
  ct_idx_39_tmp_tmp = t204_tmp * t20;
  ct_idx_39_tmp = ct_idx_39_tmp_tmp * t35;
  ct_idx_39 = ct_idx_39_tmp * 3.2854583672995942E+99;
  ct_idx_40_tmp = t30 * t38;
  ct_idx_40 = -(ct_idx_40_tmp * 1.783956770847936E+98);
  ct_idx_49_tmp_tmp_tmp = t20 * t24;
  ct_idx_49_tmp_tmp = ct_idx_49_tmp_tmp_tmp * t25;
  ct_idx_49_tmp = ct_idx_49_tmp_tmp * t35;
  ct_idx_49 = ct_idx_49_tmp * 3.5679135416958708E+98;
  ct_idx_50_tmp = t4 * t6;
  b_ct_idx_50_tmp = t6 * t18;
  c_ct_idx_50_tmp = t206_tmp * t6;
  ct_idx_50_tmp_tmp = t2 * t25;
  d_ct_idx_50_tmp = ct_idx_50_tmp_tmp * t35;
  e_ct_idx_50_tmp = t6 * t9;
  f_ct_idx_50_tmp = ct_idx_50_tmp * t9;
  g_ct_idx_50_tmp = t9 * t30;
  h_ct_idx_50_tmp = t9 * t32;
  i_ct_idx_50_tmp = t413_tmp * t25;
  t22 = t9 * t20;
  j_ct_idx_50_tmp = t22 * t25;
  k_ct_idx_50_tmp = t199_tmp * t25;
  l_ct_idx_50_tmp = t19 * t24;
  b_ct_idx_50_tmp_tmp = t3 * t24;
  m_ct_idx_50_tmp = b_ct_idx_50_tmp_tmp * t35;
  c_ct_idx_50_tmp_tmp = t275_tmp_tmp * t20;
  n_ct_idx_50_tmp = c_ct_idx_50_tmp_tmp * t35;
  o_ct_idx_50_tmp = t9 * t24 * t35;
  p_ct_idx_50_tmp = t275_tmp_tmp * t25 * t35;
  q_ct_idx_50_tmp = t24 * t35;
  r_ct_idx_50_tmp = t108_tmp * t9;
  s_ct_idx_50_tmp = t153_tmp * t25;
  t_ct_idx_50_tmp = t145_tmp * t35;
  u_ct_idx_50_tmp = -(b_ct_idx_50_tmp * 5.3227998669959494E+97);
  v_ct_idx_50_tmp = -(d_ct_idx_50_tmp * 2.046764220388046E+97);
  ct_idx_50 =
      (((((((((((((((((((((((((((((((((((-(t4 * 2.6371840387918691E+98) +
                                         -(t3 * 3.9642799292040432E+98)) +
                                        t9 * 3.0846921754017772E+98) +
                                       t6 * 1.024176574588261E+98) +
                                      -(t206_tmp * 3.17632432794494E+98)) +
                                     t96) +
                                    ct_idx_50_tmp * 8.20607280028577E+97) +
                                   t108_tmp * 1.233557052569721E+98) +
                                  t236_tmp * 1.4895706578535441E+98) +
                                 t116_tmp * 3.6476145764072429E+98) +
                                c_ct_idx_50_tmp * 9.8837048491980743E+97) +
                               t118) +
                              -(e_ct_idx_50_tmp * 9.5985749137990415E+97)) +
                             -(r_ct_idx_50_tmp * 4.6350672079433329E+97)) +
                            u_ct_idx_50_tmp) +
                           t5 * 5.3941415982838437E+97) +
                          -(f_ct_idx_50_tmp * 1.1350209284253789E+98)) +
                         t159) +
                        -(g_ct_idx_50_tmp * 4.6971912267892741E+97)) +
                       -(h_ct_idx_50_tmp * 7.8821205926953869E+96)) +
                      t443_tmp * 3.899903300635676E+97) +
                     t270_tmp * 9.0516379936292747E+96) +
                    i_ct_idx_50_tmp * 4.6971912267892741E+97) +
                   q_ct_idx_50_tmp * 6.5442317826334076E+96) +
                  -(s_ct_idx_50_tmp * 8.9115596653707073E+96)) +
                 -(j_ct_idx_50_tmp * 5.3941415982838437E+97)) +
                l_ct_idx_50_tmp * 2.1466839893371438E+97) +
               m_ct_idx_50_tmp * 7.8821205926953869E+96) +
              -(k_ct_idx_50_tmp * 1.0733419946685719E+97)) +
             -(t_ct_idx_50_tmp * 8.9115596653707073E+96)) +
            t397_tmp * 1.2326001695664929E+97) +
           v_ct_idx_50_tmp) +
          -(n_ct_idx_50_tmp * 1.0733419946685719E+97)) +
         t430_tmp * 1.2326001695664929E+97) +
        -(o_ct_idx_50_tmp * 9.0516379936292747E+96)) +
       -(p_ct_idx_50_tmp * 2.4652003391329851E+97)) -
      3.2913942895006169E+98;
  ct_idx_51_tmp = t4 * t24;
  b_ct_idx_51_tmp = t236_tmp * t24;
  c_ct_idx_51_tmp = t236_tmp * t20;
  ct_idx_51_tmp_tmp = t2 * t7;
  d_ct_idx_51_tmp = ct_idx_51_tmp_tmp * t25;
  e_ct_idx_51_tmp = t275_tmp * t24;
  f_ct_idx_51_tmp = t275_tmp * t20;
  g_ct_idx_51_tmp = t206_tmp * t9;
  h_ct_idx_51_tmp = t18 * t32;
  i_ct_idx_51_tmp = t7 * t38;
  j_ct_idx_51_tmp = ct_idx_51_tmp * t35;
  k_ct_idx_51_tmp = b_ct_idx_51_tmp * t35;
  l_ct_idx_51_tmp = t6 * t7;
  m_ct_idx_51_tmp = t7 * t33;
  n_ct_idx_51_tmp = t18 * t30;
  o_ct_idx_51_tmp = c_ct_idx_51_tmp * t25;
  ct_idx_51 =
      1.0 /
      ((((((((((((((((((((((((((((((((-(t6 * 3.9928605388461837E+110) +
                                      -(t8 * 1.215757206650896E+111)) +
                                     -(t7 * 7.46316243327777E+110)) +
                                    -(t18 * 6.66890473783269E+110)) +
                                   ct_idx_6_tmp * 3.7830473711723741E+110) +
                                  l_ct_idx_51_tmp * 2.3222973196778359E+110) +
                                 g_ct_idx_51_tmp * 1.373401503621102E+111) +
                                -(t30 * 1.953959797292265E+110)) +
                               b_ct_idx_50_tmp * 2.07514974199132E+110) +
                              -(t32 * 3.2788417613697459E+109)) +
                             -(t33 * 1.74601207814982E+110)) +
                            -(c_ct_idx_50_tmp * t9 * 4.273585975402672E+110)) +
                           -(t38 * 2.9298951419711852E+109)) +
                          m_ct_idx_51_tmp * 1.015502327157201E+110) +
                         h_ct_idx_51_tmp * 1.70406343245411E+109) +
                        n_ct_idx_51_tmp * 1.015502327157201E+110) +
                       i_ct_idx_51_tmp * 1.70406343245411E+109) +
                      ct_idx_24_tmp * 8.9298774738683466E+109) +
                     ct_idx_28_tmp * 3.5957562864376437E+110) +
                    ct_idx_29_tmp * 4.4614752376343817E+108) +
                   ct_idx_40_tmp * 4.4614752376343817E+108) +
                  j_ct_idx_51_tmp * 6.0338579596251836E+109) +
                 -(ct_idx_33_tmp * 8.2165618525715213E+109)) +
                -(o_ct_idx_51_tmp * 2.0310046543144019E+110)) +
               d_ct_idx_50_tmp * 7.9795264710044618E+109) +
              e_ct_idx_51_tmp * t25 * 4.6409917791085313E+109) +
             -(b_t254_tmp * t24 * 4.6409917791085313E+109)) +
            -(ct_idx_39_tmp * 8.2165618525715213E+109)) +
           -(d_ct_idx_51_tmp * t35 * 4.6409917791085313E+109)) +
          -(k_ct_idx_51_tmp * 3.40812686490822E+109)) +
         f_ct_idx_51_tmp * t35 * 4.6409917791085313E+109) +
        -(ct_idx_49_tmp * 8.9229504752687635E+108)) +
       1.283184824024515E+111);
  ct_idx_52_tmp = t7 * t25;
  b_ct_idx_52_tmp = t2 * t35;
  c_ct_idx_52_tmp = t25 * t32;
  d_ct_idx_52_tmp = ct_idx_51_tmp_tmp * t35;
  e_ct_idx_52_tmp = ct_idx_49_tmp_tmp_tmp * t35;
  t19 = t20 * 1.7507937695762331E+100 + t145_tmp * 2.3439735328698211E+100;
  f_ct_idx_52_tmp = t7 * t35;
  g_ct_idx_52_tmp = t30 * t35;
  ct_idx_52 =
      (((((((((((((((((((((((((((((((((((((t19 + ct_idx_28_tmp_tmp *
                                                     1.402799232857399E+100) +
                                          -t136) +
                                         -(t25 * 1.362330596779613E+100)) +
                                        -t153) +
                                       ct_idx_52_tmp * 7.9234840852483846E+99) +
                                      ct_idx_39_tmp_tmp *
                                          1.8780762936708988E+100) +
                                     -(ct_idx_51_tmp *
                                       1.3791712150019229E+100)) +
                                    -(ct_idx_50_tmp_tmp *
                                      1.8238966332642771E+100)) +
                                   -t171) +
                                  -(ct_idx_33_tmp_tmp *
                                    3.2054971876116289E+99)) +
                                 t35 * 1.3393842115009421E+100) +
                                b_ct_idx_51_tmp * 7.7900250562877808E+99) +
                               b_ct_idx_52_tmp * 3.113023442192204E+99) +
                              -t204) +
                             -(c_ct_idx_51_tmp * 7.9234840852483846E+99)) +
                            t236) +
                           -t217) +
                          t240) +
                         t247) +
                        d_ct_idx_51_tmp * 1.060800952497837E+100) +
                       e_ct_idx_51_tmp * 1.810573128102865E+99) +
                      t255) +
                     t264) +
                    t275) +
                   -t254) +
                  c_ct_idx_52_tmp * 3.4810779942854331E+98) +
                 -(f_ct_idx_51_tmp * 1.060800952497837E+100)) +
                -(f_ct_idx_52_tmp * 7.7900250562877808E+99)) +
               t312) +
              -(d_ct_idx_52_tmp * 1.810573128102865E+99)) +
             -t325) +
            -t344) +
           -t364) +
          -(g_ct_idx_52_tmp * 2.0395369812687571E+99)) +
         ct_idx_49_tmp_tmp * 2.0395369812687571E+99) +
        -(e_ct_idx_52_tmp * 3.4810779942854331E+98)) +
       t446) +
      -t443;
  ct_idx_54 =
      ((((((((((((((((((((((((((((((((((((((((t3 * 2.477674955752527E+97 +
                                              t206_tmp *
                                                  1.9852027049655879E+97) +
                                             -(t9 * 1.9279326096261111E+97)) +
                                            -(t108_tmp *
                                              7.7097315785607553E+96)) +
                                           t20 * 2.8012700313219719E+97) +
                                          e_ct_idx_50_tmp *
                                              5.9991093211244009E+96) +
                                         -(t116_tmp * 2.2797591102545272E+97)) +
                                        -(c_ct_idx_50_tmp *
                                          6.1773155307487974E+96)) +
                                       f_ct_idx_50_tmp *
                                           7.0938808026586212E+96) +
                                      ct_idx_28_tmp_tmp *
                                          2.2444787725718392E+97) +
                                     -(t25 * 2.1797289548473819E+97)) +
                                    -(t153_tmp * 6.4011035911766324E+96)) +
                                   -(t171_tmp * 2.5775055195848361E+97)) +
                                  ct_idx_52_tmp * 1.267757453639742E+97) +
                                 -(t5 * 3.3713384989274018E+96)) +
                                g_ct_idx_50_tmp * 2.9357445167432959E+96) +
                               -(ct_idx_33_tmp_tmp * 5.1287955001786067E+96)) +
                              h_ct_idx_50_tmp * 4.9263253704346168E+95) +
                             b_ct_idx_52_tmp * 4.9808375075075263E+96) +
                            b_t236_tmp * 1.4558622136163079E+97) +
                           -(t217_tmp * 1.4558622136163079E+97)) +
                          -(c_ct_idx_51_tmp * 1.267757453639742E+97)) +
                         e_ct_idx_51_tmp * 2.8969170049645831E+96) +
                        t255_tmp * 5.8897855805446754E+96) +
                       t264_tmp * 3.3267499168724679E+96) +
                      -(t270_tmp * 5.6572737460182967E+95)) +
                     c_ct_idx_52_tmp * 5.5697247908566932E+95) +
                    -(i_ct_idx_50_tmp * 2.9357445167432959E+96)) +
                   j_ct_idx_50_tmp * 3.3713384989274018E+96) +
                  -(d_ct_idx_52_tmp * 2.8969170049645831E+96)) +
                 k_ct_idx_50_tmp * 6.7083874666785744E+95) +
                -(t364_tmp * 3.3267499168724679E+96)) +
               -(t344_tmp * 6.3961381887126438E+95)) +
              -(l_ct_idx_50_tmp * 1.3416774933357149E+96)) +
             -(m_ct_idx_50_tmp * 4.9263253704346168E+95)) +
            n_ct_idx_50_tmp * 6.7083874666785744E+95) +
           -(t397_tmp * 7.7037510597905785E+95)) +
          o_ct_idx_50_tmp * 5.6572737460182967E+95) +
         p_ct_idx_50_tmp * 1.5407502119581159E+96) +
        -(t430_tmp * 7.7037510597905785E+95)) +
       -(e_ct_idx_52_tmp * 5.5697247908566932E+95)) +
      t446_tmp * 6.3961381887126438E+95;
  t270_tmp = t204_tmp * t9;
  t5 = t275_tmp_tmp * t4;
  ct_idx_55_tmp = t22 * t24;
  b_ct_idx_55_tmp = t5 * t25;
  c_ct_idx_55_tmp = t116_tmp * t24;
  t22 = t504 * t25;
  t27 = t270_tmp * t20;
  t275_tmp = t9 * t35;
  t270_tmp *= t24;
  t504 = t206_tmp * t35;
  t145_tmp = t5 * t35;
  d_ct_idx_55_tmp = b_ct_idx_50_tmp_tmp * t33;
  t74 = g_ct_idx_50_tmp * t35;
  t503 = ct_idx_55_tmp * t25;
  b_t254_tmp = i_ct_idx_50_tmp * t35;
  e_ct_idx_55_tmp = b_ct_idx_50_tmp_tmp * t25 * t35;
  ct_idx_55_tmp *= t35;
  t325 =
      (((((((((((((((((((((((((((((((((((((((((t19 + -t136) +
                                              t413_tmp *
                                                  2.1087223196099079E+100) +
                                             -t153) +
                                            c_ct_idx_50_tmp_tmp *
                                                2.823170490567743E+100) +
                                           -(b_ct_idx_50_tmp_tmp *
                                             2.0732041018543329E+100)) +
                                          -t171) +
                                         t389_tmp * 1.88430419326191E+100) +
                                        -(t199_tmp * 4.8185822366004722E+99)) +
                                       -t204) +
                                      -(b_t206_tmp * 1.9402782870958291E+100)) +
                                     c_ct_idx_55_tmp *
                                         1.9075972526767341E+100) +
                                    t22 * 2.5227181142817188E+100) +
                                   t236) +
                                  -t217) +
                                 t240) +
                                t247) +
                               -(t231_tmp * 1.9402782870958291E+100)) +
                              t270_tmp * 4.433675501661638E+99) +
                             t255) +
                            -(b_ct_idx_55_tmp * 2.5976565774822351E+100)) +
                           t264) +
                          t275) +
                         -t254) +
                        t504 * 1.9075972526767341E+100) +
                       -(t27 * 2.5976565774822351E+100)) +
                      t145_tmp * 4.433675501661638E+99) +
                     -(t275_tmp * 1.852565957254429E+100)) +
                    t312) +
                   -(t323_tmp * 4.30577066955087E+99)) +
                  -t325) +
                 d_ct_idx_55_tmp * 2.8209805279292E+99) +
                -t344) +
               -t364) +
              -(b_t389_tmp * 4.8148444123691118E+98)) +
             -(b_t413_tmp * 4.8148444123691118E+98)) +
            t74 * 2.8209805279292E+99) +
           t446) +
          -t443) +
         -(t503 * 2.8209805279292E+99)) +
        e_ct_idx_55_tmp * 4.8148444123691118E+98) +
       ct_idx_55_tmp * 4.8148444123691118E+98) +
      -(b_t254_tmp * 2.8209805279292E+99);
  t364 = t2 * t8;
  t443 = t25 * t35;
  ct_idx_56_tmp = ct_idx_51_tmp * t25;
  b_ct_idx_56_tmp = ct_idx_28_tmp_tmp * t35;
  t255 = t217_tmp * t24;
  t275 = ct_idx_52_tmp * t35;
  t236 = t5 * t9;
  t240 = b_ct_idx_51_tmp * t25;
  t254 = c_ct_idx_51_tmp * t35;
  t217 =
      ((((((((((((((((((((((((((((((((((((((((((((((-(t2 *
                                                      3.3538321486300018E+102) +
                                                    t7 *
                                                        1.456992417750339E+102) +
                                                   t8 *
                                                       2.373456356808413E+102) +
                                                  t18 *
                                                      1.301933828265091E+102) +
                                                 ct_idx_51_tmp_tmp *
                                                     1.9506304649607119E+102) +
                                                t364 *
                                                    3.1775980577810222E+102) +
                                               t254_tmp *
                                                   1.74303706583323E+102) +
                                              t32 * 6.4011035911766322E+100) +
                                             -(t413_tmp *
                                               3.3739557113758533E+101)) +
                                            b_ct_idx_50_tmp_tmp *
                                                3.3171265629669321E+101) +
                                           -(g_ct_idx_51_tmp *
                                             2.6812167029627671E+102)) +
                                          -(c_ct_idx_50_tmp_tmp *
                                            4.5170727849083889E+101)) +
                                         b_t206_tmp * 3.1044452593533271E+101) +
                                        -(t236 * 3.5896295136773182E+102)) +
                                       t199_tmp * 7.7097315785607555E+100) +
                                      t38 * 5.7198741750830758E+100) +
                                     -(t389_tmp * 3.0148867092190553E+101)) +
                                    t231_tmp * 3.1044452593533271E+101) +
                                   b_ct_idx_55_tmp * 4.1562505239715749E+101) +
                                  -(c_ct_idx_55_tmp *
                                    3.0521556042827752E+101)) +
                                 -(t22 * 4.0363489828507507E+101)) +
                                t27 * 4.1562505239715749E+101) +
                               ct_idx_49_tmp_tmp_tmp *
                                   3.7503576525917138E+101) +
                              -(h_ct_idx_51_tmp * 3.3267499168724678E+100)) +
                             t275_tmp * 2.964105531607087E+101) +
                            t323_tmp * 6.8892330712813928E+100) +
                           -(t270_tmp * 7.09388080265862E+100)) +
                          -(t504 * 3.0521556042827752E+101)) +
                         -(i_ct_idx_51_tmp * 3.3267499168724678E+100)) +
                        -(ct_idx_56_tmp * 3.4507803395913723E+101)) +
                       -(t145_tmp * 7.09388080265862E+100)) +
                      t443 * 3.3512305462379441E+101) +
                     b_t389_tmp * 7.7037510597905788E+99) +
                    -(d_ct_idx_55_tmp * 4.51356884468672E+100)) +
                   b_t413_tmp * 7.7037510597905788E+99) +
                  -(b_ct_idx_56_tmp * 3.4507803395913723E+101)) +
                 t240 * 1.9491173406722068E+101) +
                -(t255 * 1.9491173406722068E+101)) +
               -(j_ct_idx_51_tmp * 1.1779571161089351E+101)) +
              t254 * 1.9491173406722068E+101) +
             -(t275 * 1.9491173406722068E+101)) +
            k_ct_idx_51_tmp * 6.6534998337449356E+100) +
           -(t74 * 4.51356884468672E+100)) +
          t503 * 4.51356884468672E+100) +
         b_t254_tmp * 4.51356884468672E+100) +
        -(e_ct_idx_55_tmp * 7.7037510597905788E+99)) +
       -(ct_idx_55_tmp * 7.7037510597905788E+99)) -
      2.5050916094759448E+102;
  t204 = t206_tmp * 4.295141349249055E+65;
  t171 = -(t9 * 4.1712330178969239E+65);
  t446 = e_ct_idx_50_tmp * 1.2979542310402759E+65;
  t344 = -(c_ct_idx_50_tmp * 1.3365105385516521E+65);
  t312 = g_ct_idx_50_tmp * 6.3517129173536425E+64;
  t264 = h_ct_idx_50_tmp * 1.06584903120889E+64;
  t247 = -(i_ct_idx_50_tmp * 6.3517129173536425E+64);
  t153 = k_ct_idx_50_tmp * 1.45141210632265E+64;
  t136 = -(l_ct_idx_50_tmp * 2.9028242126453008E+64);
  b_ct_idx_55_tmp = -(m_ct_idx_50_tmp * 1.06584903120889E+64);
  c_ct_idx_55_tmp = n_ct_idx_50_tmp * 1.45141210632265E+64;
  t5 = cos(in1[0] + 1.5707963267948966) * 0.4667 + t55;
  t22 = -k + t72;
  t74 = -h + t5;
  t503 = t52 * t74 * 2.0 + -(t51 * t22 * 2.0);
  t504 = t53 * t74 * 2.0 + -(t55 * t22 * 2.0);
  d_ct_idx_55_tmp = t503 * ct_idx_51;
  t116_tmp = -(f_ct_idx_50_tmp * 1.4187761605317239E+100);
  t275_tmp_tmp = -(j_ct_idx_50_tmp * 6.7426769978548048E+99);
  t204_tmp = -(o_ct_idx_50_tmp * 1.131454749203659E+99);
  t108_tmp = -(p_ct_idx_50_tmp * 3.0815004239162308E+99);
  t430_tmp = -(t413_tmp * 6.7479114227517073E+100);
  t397_tmp = -(t389_tmp * 6.0297734184381112E+100);
  t270_tmp = -(t270_tmp * 1.4187761605317239E+100);
  t145_tmp = -(t145_tmp * 1.4187761605317239E+100);
  b_t254_tmp = -(e_ct_idx_55_tmp * 1.5407502119581159E+99);
  t275_tmp = -(ct_idx_55_tmp * 1.5407502119581159E+99);
  t27 =
      d_ct_idx_55_tmp *
      (((((((((((((((((((((((((((((((((((((((((((((((((-(t3 *
                                                         4.9553499115050528E+100) +
                                                       t6 *
                                                           3.193154826116699E+100) +
                                                      t8 *
                                                          9.7226060215097672E+100) +
                                                     t108) +
                                                    t116) +
                                                   -(t20 *
                                                     5.6025400626439448E+100)) +
                                                  t30 *
                                                      1.562613093059536E+100) +
                                                 t32 * 2.622142519762599E+99) +
                                                -(ct_idx_6_tmp *
                                                  3.02536385960975E+100)) +
                                               t33 * 1.3963139557619591E+100) +
                                              t430_tmp) +
                                             t171_tmp *
                                                 5.1550110391696713E+100) +
                                            t153_tmp *
                                                1.2802207182353259E+100) +
                                           t180) +
                                          t116_tmp) +
                                         t199) +
                                        t206) +
                                       t38 * 2.3430842929727389E+99) +
                                      t217_tmp * 2.9117244272326148E+100) +
                                     t397_tmp) +
                                    t231) +
                                   -(b_t236_tmp * 2.9117244272326148E+100)) +
                                  t270) +
                                 -(t264_tmp * 6.6534998337449362E+99)) +
                                t270_tmp) +
                               -(t255_tmp * 1.1779571161089351E+100)) +
                              -(ct_idx_24_tmp * 7.1413667156412446E+99)) +
                             t323) +
                            -(ct_idx_28_tmp * 2.875584165255047E+100)) +
                           -(ct_idx_29_tmp * 3.5679135416958708E+98)) +
                          t145_tmp) +
                         t275_tmp_tmp) +
                        ct_idx_33_tmp * 6.5709167345991884E+99) +
                       t364_tmp * 6.6534998337449362E+99) +
                      t344_tmp * 1.279227637742529E+99) +
                     t389) +
                    t397) +
                   ct_idx_39_tmp * 6.5709167345991884E+99) +
                  -(ct_idx_40_tmp * 3.5679135416958708E+98)) +
                 t413) +
                -(j_ct_idx_51_tmp * 4.8253733072899684E+99)) +
               -(d_ct_idx_50_tmp * 6.3813557255813289E+99)) +
              t430) +
             t204_tmp) +
            t108_tmp) +
           -(t446_tmp * 1.279227637742529E+99)) +
          b_t254_tmp) +
         t275_tmp) +
        ct_idx_49_tmp * 7.1358270833917428E+98) -
       1.0261835528113919E+101) *
      1.0E+10;
  t19 = (t42 * t74 * 0.9334 + -(t41 * t22 * 0.9334)) * ct_idx_51;
  t5 = (t72 * t74 * 2.0 + -(t5 * t22 * 2.0)) * ct_idx_51;
  t22 = t504 * ct_idx_51;
  b_LgLf_psw_ub[0] =
      (((t5 *
             ((((((((t4 * -1.664297110460606E+69 +
                     t6 * 4.3795417961373631E+68) +
                    (t7 * 8.1859187141425319E+68 +
                     t30 * 2.1431874509412249E+68)) +
                   (t32 * 3.5963751794318893E+67 +
                    ct_idx_50_tmp * 5.178760014034365E+68)) +
                  (t236_tmp * 9.4005124603600386E+68 -
                   l_ct_idx_51_tmp * 2.5471959452723208E+68)) +
                 (t443_tmp * 2.4611849984110969E+68 +
                  q_ct_idx_50_tmp * 4.1299908864194451E+67)) +
                (r_ct_idx_50_tmp * -2.9251386507347238E+68 -
                 ct_idx_24_tmp * 9.7946750833659731E+67)) +
               (s_ct_idx_50_tmp * -5.6239848196443146E+67 -
                t_ct_idx_50_tmp * 5.6239848196443146E+67)) +
              -1.407452505368112E+69) *
             1.9807040628566081E+41 -
         t22 *
             (((((((((((((t4 * -5.2743680775837369E+98 +
                          t6 * 1.7181426729130289E+98) +
                         t7 * 1.2971105964252839E+98) +
                        ((t30 * 3.3960160732340671E+97 +
                          t32 * 5.6986839435659248E+96) +
                         t96)) +
                       ((((t118 + u_ct_idx_50_tmp) + t159) + v_ct_idx_50_tmp) +
                        ct_idx_50_tmp * 1.6412145600571541E+98)) +
                      t236_tmp * 2.9791413157070881E+98) +
                     l_ct_idx_51_tmp * -4.036193086154212E+97) +
                    t443_tmp * 7.7998066012713534E+97) +
                   q_ct_idx_50_tmp * 1.3088463565266821E+97) +
                  r_ct_idx_50_tmp * -9.2701344158866658E+97) +
                 ct_idx_24_tmp * -1.55202821855867E+97) +
                s_ct_idx_50_tmp * -1.7823119330741418E+97) +
               t_ct_idx_50_tmp * -1.7823119330741418E+97) +
              -5.5215918060288816E+98) *
             1.25E+12) +
        t503 * ct_idx_50 * ct_idx_51 * 1.25E+12) -
       t19 * ct_idx_52 * 3.2E+10) +
      d_ct_idx_55_tmp * ct_idx_54 * 2.0E+13;
  b_LgLf_psw_ub[1] =
      (((t27 - d_ct_idx_55_tmp *
                   (((((((((t6 * 2.2366877721760131E+100 +
                            t8 * 4.8613030107548844E+100) +
                           t18 * 1.069116981453385E+100) +
                          t32 * 1.3110712598813E+99) +
                         t33 * 9.78066683590667E+99) +
                        ((((((((((((((((((((t38 * 1.641244559896035E+99 +
                                            -(t3 * 4.9553499115050528E+100)) +
                                           t108) +
                                          t116) +
                                         ct_idx_5) +
                                        ct_idx_6) +
                                       t180) +
                                      t116_tmp) +
                                     t270) +
                                    ct_idx_24) +
                                   ct_idx_28) +
                                  ct_idx_29) +
                                 t275_tmp_tmp) +
                                ct_idx_33) +
                               t397) +
                              ct_idx_39) +
                             ct_idx_40) +
                            t430) +
                           t204_tmp) +
                          t108_tmp) +
                         ct_idx_49)) +
                       b_ct_idx_50_tmp * -3.3267499168724681E+99) +
                      d_ct_idx_50_tmp * -4.4699055005331928E+99) +
                     j_ct_idx_51_tmp * -2.4126866536449842E+99) +
                    -7.1880391949948467E+100) *
                   2.0E+10) +
        t504 * ct_idx_50 * ct_idx_51 * 1.25E+12) +
       t19 * t325 * 3.2E+10) +
      t5 *
          (((((((((((((((t4 * 3.566096229827739E+65 + t204) + t171) + t446) +
                      t344) +
                     t312) +
                    t264) +
                   t247) +
                  t153) +
                 t136) +
                b_ct_idx_55_tmp) +
               c_ct_idx_55_tmp) -
              ct_idx_50_tmp * 1.1096550276482461E+65) +
             (t236_tmp * -2.0142516521020009E+65 -
              t443_tmp * 5.27359116865459E+64)) +
            (q_ct_idx_50_tmp * -8.84934837458634E+63 +
             r_ct_idx_50_tmp * 6.26770655824882E+64)) +
           (s_ct_idx_50_tmp * 1.205053528957428E+64 +
            t_ct_idx_50_tmp * 1.205053528957428E+64)) *
          9.2439458613517916E+44;
  b_LgLf_psw_ub[2] =
      (((-t27 + d_ct_idx_55_tmp *
                    (((((((((((((t6 * 1.59657741305835E+100 +
                                 t7 * 1.4569924177503392E+101) +
                                t8 * 2.8595866578839019E+101) +
                               t18 * 1.301933828265091E+101) +
                              t32 * 7.7121748510579323E+99) +
                             t33 * 6.9815697788097973E+99) +
                            (((((((((((((((((((((t38 * 6.8914163215694463E+99 +
                                                 ct_idx_5) +
                                                ct_idx_6) +
                                               t430_tmp) +
                                              t199) +
                                             t206) +
                                            t397_tmp) +
                                           t231) +
                                          t270_tmp) +
                                         ct_idx_24) +
                                        t323) +
                                       ct_idx_28) +
                                      ct_idx_29) +
                                     t145_tmp) +
                                    ct_idx_33) +
                                   t389) +
                                  ct_idx_39) +
                                 ct_idx_40) +
                                t413) +
                               b_t254_tmp) +
                              t275_tmp) +
                             ct_idx_49)) +
                           i_ct_idx_51_tmp * -3.3267499168724681E+99) +
                          h_ct_idx_51_tmp * -3.3267499168724681E+99) +
                         g_ct_idx_51_tmp * -2.681216702962767E+101) +
                        d_ct_idx_50_tmp * -3.190677862790664E+99) +
                       j_ct_idx_51_tmp * -1.4192257814734329E+100) +
                      k_ct_idx_51_tmp * 6.6534998337449362E+99) +
                     -3.018183385881641E+101) *
                    2.0E+10) -
        t19 * t217 * 2.0E+9) -
       t22 * ct_idx_54 * 2.0E+13) +
      t5 *
          ((((((((((((((((t25 * -4.716014108132451E+65 + t204) + t171) + t446) +
                       t344) +
                      t312) +
                     t264) +
                    t247) +
                   t153) +
                  t136) +
                 b_ct_idx_55_tmp) +
                c_ct_idx_55_tmp) +
               ct_idx_28_tmp_tmp * 4.8561054039830056E+65) +
              (ct_idx_52_tmp * 2.742892424197626E+65 +
               b_ct_idx_52_tmp * 1.0776431584983669E+65)) +
             (c_ct_idx_52_tmp * 1.205053528957428E+64 -
              ct_idx_33_tmp_tmp * 1.1096550276482461E+65)) +
            (c_ct_idx_51_tmp * -2.742892424197626E+65 -
             d_ct_idx_52_tmp * 6.26770655824882E+64)) +
           (e_ct_idx_52_tmp * -1.205053528957428E+64 +
            e_ct_idx_51_tmp * 6.26770655824882E+64)) *
          9.2439458613517916E+44;
  b_LgLf_psw_ub[3] =
      (((t5 *
             ((((((((((t25 * 2.9475088175827819E+68 -
                       t35 * 2.8978625179985142E+68) +
                      (ct_idx_28_tmp_tmp * -3.0350658774893788E+68 +
                       ct_idx_50_tmp_tmp * 3.94614304458412E+68)) +
                     (ct_idx_51_tmp * 2.983944812502915E+68 -
                      ct_idx_52_tmp * 1.7143077651235159E+68)) +
                    (b_ct_idx_52_tmp * -6.7352697406147925E+67 +
                     f_ct_idx_52_tmp * 1.6854328601938829E+68)) +
                   (c_ct_idx_52_tmp * -7.531584555983923E+66 +
                    g_ct_idx_52_tmp * 4.412697806454926E+67)) +
                  (ct_idx_39_tmp_tmp * -4.0633649782026259E+68 +
                   ct_idx_33_tmp_tmp * 6.935343922801539E+67)) +
                 (c_ct_idx_51_tmp * 1.7143077651235159E+68 -
                  d_ct_idx_51_tmp * 2.2951258443279339E+68)) +
                (b_ct_idx_51_tmp * -1.6854328601938829E+68 +
                 d_ct_idx_52_tmp * 3.9173165989055133E+67)) +
               (ct_idx_49_tmp_tmp * -4.412697806454926E+67 +
                e_ct_idx_52_tmp * 7.531584555983923E+66)) +
              (f_ct_idx_51_tmp * 2.2951258443279339E+68 -
               e_ct_idx_51_tmp * 3.9173165989055133E+67)) *
             1.479031337816287E+42 +
         t22 * ct_idx_52 * 3.2E+10) -
        d_ct_idx_55_tmp * t325 * 3.2E+10) -
       d_ct_idx_55_tmp * t217 * 2.0E+9) +
      t19 *
          (((((((((((((((((((((((((((((t2 * -4.1922901857875019E+105 +
                                       t7 * 6.1560105058131068E+105) +
                                      t8 * 1.002820748385332E+106) +
                                     t18 * 5.50086481372941E+105) +
                                    t30 * 1.3733161713845791E+105) +
                                   t32 * 4.0006897444853948E+103) +
                                  t33 * 1.2271627214023409E+105) +
                                 t38 * 3.574921359426923E+103) +
                                ct_idx_51_tmp_tmp * 2.43828808120089E+105) +
                               t364 * 3.9719975722262778E+105) +
                              t254_tmp * 2.1787963322915381E+105) +
                             m_ct_idx_51_tmp * -7.1373309210161707E+104) +
                            ct_idx_49_tmp_tmp_tmp * 4.687947065739642E+104) +
                           i_ct_idx_51_tmp * -2.0792186980452929E+103) +
                          n_ct_idx_51_tmp * -7.1373309210161707E+104) +
                         h_ct_idx_51_tmp * -2.0792186980452929E+103) +
                        t443 * 4.1890381827974309E+104) +
                       g_ct_idx_51_tmp * -1.1328540897478209E+106) +
                      ct_idx_28_tmp * -2.5272322712911758E+105) +
                     ct_idx_56_tmp * -4.3134754244892159E+104) +
                    b_ct_idx_56_tmp * -4.3134754244892159E+104) +
                   t255 * -2.436396675840258E+104) +
                  j_ct_idx_51_tmp * -7.3622319756808429E+103) +
                 t275 * -2.436396675840258E+104) +
                t236 * -4.487036892096648E+105) +
               o_ct_idx_51_tmp * 1.4274661842032339E+105) +
              t240 * 2.436396675840258E+104) +
             t254 * 2.436396675840258E+104) +
            k_ct_idx_51_tmp * 4.158437396090585E+103) +
           -1.0584386080587479E+106) *
          3.2E+6;
}

/* End of code generation (LgLf_psw_ub.c) */
