/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * CBF_Lfs3.c
 *
 * Code generation for function 'CBF_Lfs3'
 *
 */

/* Include files */
#include "CBF_Lfs3.h"
#include <math.h>

/* Function Definitions */
double CBF_Lfs3(const double in1[10], double xmin)
{
  double t8;
  double t14;
  double Lfs3_tmp;
  (void)xmin;

  /* CBF_LFS3 */
  /*     LFS3 = CBF_LFS3(IN1,XMIN) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:01:59 */
  t8 = (((in1[0] + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469;
  t14 = sin(-in1[4] + t8) * 0.4667;
  t8 = sin(t8) * 0.4064 + t14;
  Lfs3_tmp = sin((in1[0] + in1[1]) + 1.5707963267948966) * 0.4064 + t8;
  return (((-in1[6] * Lfs3_tmp - in1[5] * (Lfs3_tmp + sin(in1[0] +
              1.5707963267948966) * 0.4667)) + in1[8] * t8) + in1[9] * t14) -
    in1[7] * t8;
}

/* End of code generation (CBF_Lfs3.c) */
