/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * p_swing.c
 *
 * Code generation for function 'p_swing'
 *
 */

/* Include files */
#include "p_swing.h"
#include <math.h>

/* Function Definitions */
void p_swing(const double in1[5], double pfoot2[2])
{
  double t8;
  double t7;
  double t9;

  /* P_SWING */
  /*     PFOOT2 = P_SWING(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:00:39 */
  t8 = (((in1[0] + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469;
  t7 = in1[1] + (in1[0] + 1.5707963267948966);
  t9 = -in1[4] + t8;
  pfoot2[0] = ((cos(in1[0] + 1.5707963267948966) * 0.4667 + cos(t7) * 0.4064) +
               cos(t8) * 0.4064) + cos(t9) * 0.4667;
  pfoot2[1] = ((sin(in1[0] + 1.5707963267948966) * 0.4667 + sin(t7) * 0.4064) +
               sin(t8) * 0.4064) + sin(t9) * 0.4667;
}

/* End of code generation (p_swing.c) */
