/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * CBF_s3.c
 *
 * Code generation for function 'CBF_s3'
 *
 */

/* Include files */
#include "CBF_s3.h"
#include <math.h>

/* Function Definitions */
double CBF_s3(const double in1[5], double xmin)
{
  /* CBF_S3 */
  /*     S3 = CBF_S3(IN1,XMIN) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:01:59 */
  return (((-xmin + cos((in1[0] + in1[1]) + 1.5707963267948966) * 0.4064) + cos
           (in1[0] + 1.5707963267948966) * 0.4667) + cos(((((-in1[4] + in1[0]) +
              in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469) * 0.4667) + cos
    ((((in1[0] + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469) * 0.4064;
}

/* End of code generation (CBF_s3.c) */
