/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * t_lb.c
 *
 * Code generation for function 't_lb'
 *
 */

/* Include files */
#include "t_lb.h"

/* Function Definitions */
double t_lb(const double in1[10], double lb)
{
  /* T_LB */
  /*     T_LB = T_LB(IN1,LB) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     04-Dec-2021 16:54:26 */
  return ((-lb + in1[0]) + in1[2]) + in1[1];
}

/* End of code generation (t_lb.c) */
