function Js3q = CBF_Js3q(in1,xmin)
%CBF_JS3Q
%    JS3Q = CBF_JS3Q(IN1,XMIN)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Nov-2020 17:24:14

qnsh = in1(4,:);
qnsk = in1(5,:);
qsf = in1(1,:);
qsh = in1(3,:);
qsk = in1(2,:);
t2 = -qnsh;
t3 = -qnsk;
t4 = pi./2.0;
t5 = pi.*(3.0./2.0);
t6 = qsf+qsk+t4;
t8 = qsf+qsh+qsk+t2+t5;
t7 = sin(t6);
t9 = sin(t8);
t10 = t3+t8;
t11 = sin(t10);
t12 = t7.*(2.54e+2./6.25e+2);
t14 = t9.*(2.54e+2./6.25e+2);
t13 = -t12;
t15 = -t14;
t16 = t11.*4.667e-1;
t17 = -t16;
Js3q = [t13+t15+t17-sin(qsf+t4).*4.667e-1,t13+t15+t17,t15+t17,t14+t16,t16];
