function Lf_psw_lb = Lf_psw_lb(in1,h,k,r,lb)
%Lf_psw_lb
%    Lf_psw_lb = Lf_psw_lb(IN1,H,K,R,LB)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Dec-2021 00:43:51

dqnsh = in1(9,:);
dqnsk = in1(10,:);
dqsf = in1(6,:);
dqsh = in1(8,:);
dqsk = in1(7,:);
qnsh = in1(4,:);
qnsk = in1(5,:);
qsf = in1(1,:);
qsh = in1(3,:);
qsk = in1(2,:);
t2 = -h;
t3 = -k;
t4 = -qnsh;
t5 = -qnsk;
t6 = pi./2.0;
t7 = pi.*(3.0./2.0);
t8 = qsf+t6;
t14 = qsf+qsh+qsk+t4+t7;
t9 = cos(t8);
t10 = qsk+t8;
t11 = sin(t8);
t15 = cos(t14);
t16 = sin(t14);
t17 = t5+t14;
t12 = cos(t10);
t13 = sin(t10);
t18 = cos(t17);
t19 = sin(t17);
t22 = t9.*4.667e-1;
t23 = t11.*4.667e-1;
t24 = t16.*(2.54e+2./6.25e+2);
t25 = t15.*(2.54e+2./6.25e+2);
t20 = t12.*(2.54e+2./6.25e+2);
t21 = t13.*(2.54e+2./6.25e+2);
t26 = t18.*4.667e-1;
t27 = t19.*4.667e-1;
t28 = t25+t26;
t29 = t24+t27;
t30 = t3+t21+t23+t29;
t31 = t2+t20+t22+t28;
t32 = t29.*t31.*2.0;
t33 = t28.*t30.*2.0;
t34 = -t33;
t35 = t32+t34;
Lf_psw_lb = dqnsh.*t35-dqsh.*t35+dqsf.*(t30.*(t20+t22+t28).*2.0-t31.*(t21+t23+t29).*2.0)+dqsk.*(t30.*(t20+t28).*2.0-t31.*(t21+t29).*2.0)-dqnsk.*(t18.*t30.*9.334e-1-t19.*t31.*9.334e-1);
