/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * C_matrix.c
 *
 * Code generation for function 'C_matrix'
 *
 */

/* Include files */
#include "C_matrix.h"
#include <math.h>

/* Function Definitions */
void C_matrix(const double in1[5], const double in2[5], double C[25])
{
  double t2;
  double t3;
  double t5;
  double t6;
  double t12;
  double t16;
  double t23;
  double t24;
  double t37;
  double t15;
  double t18;
  double t20;
  double t21;
  double t25;
  double t26;
  double t44;
  double t17;
  double t29;
  double t30;
  double t33;
  double t45;
  double t46;
  double t47;
  double t42;
  double t43;
  double t48;
  double t53;
  double t49;
  double t50;
  double t51;
  double t55;
  double t63;
  double t66;
  double t68;
  double t58;
  double t60;
  double t65;
  double t67;
  double t69;
  double t70;
  double t61;

  /* C_MATRIX */
  /*     C = C_MATRIX(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:00:39 */
  t2 = sin(in1[4]);
  t3 = sin(in1[2]);
  t5 = in1[2] + in1[1];
  t6 = sin(t5);
  t12 = in1[3] + -in1[2];
  t16 = ((in2[0] + in2[2]) + in2[1]) + -in2[3];
  t23 = in2[0] * t3 * 1.506081824;
  t24 = in2[1] * t3 * 1.506081824;
  t37 = in2[4] * t2 * 0.05952683917824;
  t15 = sin(t12);
  t18 = sin(t5 + -in1[3]);
  t20 = -in2[4] + t16;
  t21 = sin((in1[3] + in1[4]) - t5);
  t25 = t6 * 3.459096394;
  t26 = in2[0] * t6 * 1.729548197;
  t44 = t2 * t16 * 0.05952683917824;
  t17 = sin(in1[4] + t12);
  t29 = in2[0] * t15 * 0.3487631994496;
  t30 = in2[1] * t15 * 0.3487631994496;
  t12 = t18 * 0.8010225648776;
  t33 = in2[0] * t18 * 0.4005112824388;
  t45 = t21 * 0.13671838506144;
  t46 = t2 * t20 * 0.05952683917824;
  t47 = in2[0] * t21 * 0.06835919253072;
  t5 = t17 * 0.11905367835648;
  t42 = in2[0] * t17 * 0.05952683917824;
  t43 = in2[1] * t17 * 0.05952683917824;
  t48 = t15 * 0.6975263988992 + t5;
  t53 = -(t2 * 0.11905367835648) + t5;
  t5 = ((t25 + sin(in1[1]) * 7.3760932192376) + -t12) + t45;
  t49 = in2[3] * t48 / 2.0;
  t50 = in2[0] * t48 / 2.0;
  t51 = in2[1] * t48 / 2.0;
  t16 = t3 * 3.012163648 + t48;
  t55 = in2[4] * t53 / 2.0;
  t63 = in2[0] * t5 / 2.0;
  t66 = t45 + t53;
  t68 = (-t12 + t45) + t48;
  t58 = in2[0] * t16 / 2.0;
  t60 = in2[1] * t16 / 2.0;
  t65 = -(in2[1] * t5 / 2.0);
  t67 = in2[4] * t66 / 2.0;
  t69 = in2[3] * t68 / 2.0;
  t70 = in2[0] * t68 / 2.0;
  t61 = -(in2[2] * t16 / 2.0);
  t5 = -(in2[2] * (((t25 + -t12) + t45) + t16) / 2.0);
  C[0] = ((t65 + t67) + t69) + t5;
  t16 = t49 + t55;
  t12 = t16 + t61;
  C[1] = t12 + t63;
  C[2] = ((((((((t23 + t24) + t26) + t29) + t30) - t33) + -t37) + t42) + t43) +
    t47;
  C[3] = (t37 + -t51) - t70;
  t45 = (in2[2] * t2 * 0.05952683917824 + -(in2[3] * t2 * 0.05952683917824)) +
    -(in2[1] * t53 / 2.0);
  C[4] = t45 - in2[0] * t66 / 2.0;
  C[5] = (((-t63 + t65) + t67) + t69) + t5;
  C[6] = t12;
  C[7] = (-t37 + t58) + t60;
  C[8] = (t37 - t50) + -t51;
  C[9] = t45 - in2[0] * t53 / 2.0;
  C[10] = (((((((((((((((((((((((-t23 - t24) - t26) - t29) - t30) + t33) + -t37)
    - t42) - t43) - t47) + in2[3] * t15 * 0.3487631994496) + in2[3] * t17 *
                       0.05952683917824) - in2[3] * t18 * 0.4005112824388) +
                     in2[4] * t17 * 0.05952683917824) + in2[3] * t21 *
                    0.06835919253072) + in2[4] * t21 * 0.06835919253072) - in2[2]
                  * t3 * 1.506081824) - in2[2] * t6 * 1.729548197) - in2[1] * t6
                * 1.729548197) - in2[2] * t15 * 0.3487631994496) - in2[2] * t17 *
              0.05952683917824) + in2[2] * t18 * 0.4005112824388) - in2[2] * t21
            * 0.06835919253072) + in2[1] * t18 * 0.4005112824388) - in2[1] * t21
    * 0.06835919253072;
  C[11] = ((t16 - t58) - t60) + t61;
  C[12] = -t37;
  C[13] = t37;
  C[14] = t44;
  C[15] = (((-t67 - t69) + t70) + in2[2] * t68 / 2.0) + in2[1] * t68 / 2.0;
  C[16] = (((-t49 + t50) + t51) - t55) + in2[2] * t48 / 2.0;
  C[17] = t37;
  C[18] = -t37;
  C[19] = -t44;
  C[20] = t20 * ((t2 * -4064.0 + t17 * 4064.0) + t21 * 4667.0) * 1.464735216E-5;
  C[21] = t20 * (t2 - t17) * -0.05952683917824;
  C[22] = -t46;
  C[23] = t46;
  C[24] = 0.0;
}

/* End of code generation (C_matrix.c) */
