/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * D_matrix.c
 *
 * Code generation for function 'D_matrix'
 *
 */

/* Include files */
#include "D_matrix.h"
#include <math.h>

/* Function Definitions */
void D_matrix(const double in1[5], double D[25])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t10;
  double t18;
  double t28;
  double t30;
  double t11;
  double t15;
  double t17;
  double t20;
  double t14;
  double t26;
  double t36;
  double t23;
  double t33;
  double t41;
  double t42;
  double t43;

  /* D_MATRIX */
  /*     D = D_MATRIX(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:00:38 */
  t2 = cos(in1[4]);
  t3 = cos(in1[2]);
  t4 = cos(in1[1]);
  t5 = in1[2] + in1[1];
  t6 = cos(t5);
  t10 = in1[3] + -in1[2];
  t18 = t3 * 3.012163648;
  t28 = t2 * 0.11905367835648;
  t30 = t2 * 0.05952683917824;
  t11 = cos(t10);
  t15 = cos(t5 + -in1[3]);
  t17 = cos((in1[3] + in1[4]) - t5);
  t20 = t6 * 1.729548197;
  t14 = cos(in1[4] + t10);
  t2 = t11 * 0.3487631994496;
  t26 = t15 * 0.4005112824388;
  t36 = t17 * 0.06835919253072;
  t23 = -(t11 * 0.6975263988992);
  t5 = t14 * 0.05952683917824;
  t33 = -(t14 * 0.11905367835648);
  t41 = t5 + (-t30 - 0.044462626260216);
  t42 = (t2 + t5) + (-t28 - 0.300577975329816);
  t43 = t36 + t41;
  t10 = (((t3 * 1.506081824 + -t2) + t28) + -t5) + 1.551021739029816;
  t3 = (t26 + t36) + t42;
  t5 = (((((((t18 + t20) + t4 * 3.6880466096188) + -(t11 * 0.6975263988992)) +
           -t26) + t28) + -(t14 * 0.11905367835648)) + -t36) +
    4.6699062266594158;
  t2 = ((t20 + -t26) + -t36) + t10;
  D[0] = (((((((t4 * 7.3760932192376 + t6 * 3.459096394) - t15 * 0.8010225648776)
              - t17 * 0.13671838506144) + t18) + t23) + t28) + t33) +
    9.2728521613209924;
  D[1] = t5;
  D[2] = t2;
  D[3] = t3;
  D[4] = t43;
  D[5] = t5;
  D[6] = (((t18 + t23) + t28) + t33) + 4.6699062266594158;
  D[7] = t10;
  D[8] = t42;
  D[9] = t41;
  D[10] = t2;
  D[11] = t10;
  D[12] = t28 + 1.551021739029816;
  D[13] = -t28 - 0.300577975329816;
  D[14] = -t30 - 0.044462626260216;
  D[15] = t3;
  D[16] = t42;
  D[17] = -t28 - 0.300577975329816;
  D[18] = t28 + 0.300577975329816;
  D[19] = t30 + 0.044462626260216;
  D[20] = t43;
  D[21] = t41;
  D[22] = -t30 - 0.044462626260216;
  D[23] = t30 + 0.044462626260216;
  D[24] = 0.044462626260216;
}

/* End of code generation (D_matrix.c) */
