function Lf_t_lb = Lf_t_lb(in1,lb)
%Lf_t_lb
%    Lf_t_lb = Lf_t_lb(IN1,LB)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Dec-2021 00:44:21

dqsf = in1(6,:);
dqsh = in1(8,:);
dqsk = in1(7,:);
Lf_t_lb = dqsf+dqsh+dqsk;
