function t_lb = t_lb(in1,lb)
%T_LB
%    T_LB = T_LB(IN1,LB)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Dec-2021 00:44:21

qsf = in1(1,:);
qsh = in1(3,:);
qsk = in1(2,:);
t_lb = -lb+qsf+qsh+qsk;
