/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Lf_psw_ub.c
 *
 * Code generation for function 'Lf_psw_ub'
 *
 */

/* Include files */
#include "Lf_psw_ub.h"
#include <math.h>

/* Function Definitions */
double Lf_psw_ub(const double in1[10], double h, double k, double r, double ub)
{
  double t10;
  double t14;
  double t17;
  double t18;
  double t19;
  double t20;
  double t21;
  double t22;
  double t23;
  double t28;
  double t35;
  (void)r;
  (void)ub;
  /* Lf_psw_ub */
  /*     Lf_psw_ub = Lf_psw_ub(IN1,H,K,R,UB) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     05-Dec-2021 00:44:00 */
  t14 = (((in1[0] + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469;
  t10 = in1[1] + (in1[0] + 1.5707963267948966);
  t17 = -in1[4] + t14;
  t18 = cos(t17);
  t19 = sin(t17);
  t22 = cos(in1[0] + 1.5707963267948966) * 0.4667;
  t23 = sin(in1[0] + 1.5707963267948966) * 0.4667;
  t20 = cos(t10) * 0.4064;
  t21 = sin(t10) * 0.4064;
  t28 = cos(t14) * 0.4064 + t18 * 0.4667;
  t17 = sin(t14) * 0.4064 + t19 * 0.4667;
  t10 = ((-k + t21) + t23) + t17;
  t14 = ((-h + t20) + t22) + t28;
  t35 = t17 * t14 * 2.0 + -(t28 * t10 * 2.0);
  return (((-in1[8] * t35 + in1[7] * t35) -
           in1[5] * (t10 * ((t20 + t22) + t28) * 2.0 -
                     t14 * ((t21 + t23) + t17) * 2.0)) -
          in1[6] * (t10 * (t20 + t28) * 2.0 - t14 * (t21 + t17) * 2.0)) +
         in1[9] * (t18 * t10 * 0.9334 - t19 * t14 * 0.9334);
}

/* End of code generation (Lf_psw_ub.c) */
