/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Lf_t_lb.c
 *
 * Code generation for function 'Lf_t_lb'
 *
 */

/* Include files */
#include "Lf_t_lb.h"

/* Function Definitions */
double Lf_t_lb(const double in1[10], double lb)
{
  (void)lb;
  /* Lf_t_lb */
  /*     Lf_t_lb = Lf_t_lb(IN1,LB) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     04-Dec-2021 16:54:26 */
  return (in1[5] + in1[7]) + in1[6];
}

/* End of code generation (Lf_t_lb.c) */
