function s3 = CBF_s3(in1,xmin)
%CBF_S3
%    S3 = CBF_S3(IN1,XMIN)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Nov-2020 22:01:59

qnsh = in1(4,:);
qnsk = in1(5,:);
qsf = in1(1,:);
qsh = in1(3,:);
qsk = in1(2,:);
t2 = -qnsh;
t3 = pi./2.0;
t4 = pi.*(3.0./2.0);
s3 = -xmin+cos(qsf+qsk+t3).*(2.54e+2./6.25e+2)+cos(qsf+t3).*4.667e-1+cos(-qnsk+qsf+qsh+qsk+t2+t4).*4.667e-1+cos(qsf+qsh+qsk+t2+t4).*(2.54e+2./6.25e+2);
