function ksi_2_dot = dz_2(in1)
%DZ_2
%    KSI_2_DOT = DZ_2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Dec-2021 23:49:52

yd1 = in1(2,:);
yd2 = in1(3,:);
yd3 = in1(4,:);
yd4 = in1(5,:);
z1 = in1(1,:);
t2 = -yd3;
t3 = pi./2.0;
t4 = pi.*(3.0./2.0);
t5 = yd1.*4.7262313860252e-1;
t6 = z1.*(1.0e+3./8.73e+2);
t7 = -t6;
et1 = cos(t2+t4+t5+t7+yd2).*8.418717978840001+cos(t3+t5+t7).*7.752247105284e+1+cos(t3+t5+t7+yd2).*3.63549771e+1;
et2 = cos(-t3+t6+yd1.*5.2737686139748e-1).*9.7255892295144e+1+cos(t2+t4+t5+t7+yd2-yd4).*1.436905246896;
ksi_2_dot = et1+et2;
