function J_pcm = J_pcm(in1)
%J_PCM
%    J_PCM = J_PCM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Nov-2020 22:00:40

qnsh = in1(4,:);
qnsk = in1(5,:);
qsf = in1(1,:);
qsh = in1(3,:);
qsk = in1(2,:);
t2 = -qnsh;
t3 = -qnsk;
t4 = pi./2.0;
t5 = pi.*(3.0./2.0);
t6 = qsf+t4;
t13 = qsf+qsh+qsk+t2+t5;
t7 = qsk+t6;
t14 = cos(t13);
t15 = sin(t13);
t16 = t3+t13;
t8 = cos(t7);
t9 = qsh+t7;
t10 = sin(t7);
t17 = cos(t16);
t18 = sin(t16);
t25 = t15.*3.981056144498277e-2;
t26 = t14.*3.981056144498277e-2;
t11 = cos(t9);
t12 = sin(t9);
t22 = t8.*3.665894385550172e-1;
t23 = t10.*3.665894385550172e-1;
t27 = -t25;
t28 = t17.*6.794859355777278e-3;
t29 = t18.*6.794859355777278e-3;
t19 = t11.*1.719159678834988e-1;
t20 = t12.*1.719159678834988e-1;
t24 = -t23;
t30 = -t28;
t31 = -t29;
t21 = -t20;
J_pcm = reshape([t21+t24+t27+t31-sin(t6).*4.599051406442227e-1,t19+t22+t26+t28+cos(t6).*4.599051406442227e-1,t21+t24+t27+t31,t19+t22+t26+t28,t21+t27+t31,t19+t26+t28,t25+t29,-t26+t30,t29,t30],[2,5]);
