/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * t_ub.c
 *
 * Code generation for function 't_ub'
 *
 */

/* Include files */
#include "t_ub.h"

/* Function Definitions */
double t_ub(const double in1[10], double ub)
{
  /* T_UB */
  /*     T_UB = T_UB(IN1,UB) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     04-Dec-2021 16:54:30 */
  return ((-in1[0] - in1[2]) - in1[1]) + ub;
}

/* End of code generation (t_ub.c) */
