/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * psw_ub.c
 *
 * Code generation for function 'psw_ub'
 *
 */

/* Include files */
#include "psw_ub.h"
#include <math.h>

/* Function Definitions */
double psw_ub(const double in1[10], double h, double k, double r, double ub)
{
  double a;
  double t7;
  double t8;
  double t9;
  /* PSW_UB */
  /*     PSW_UB = PSW_UB(IN1,H,K,R,UB) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     05-Dec-2021 00:44:00 */
  t8 = (((in1[0] + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469;
  t7 = in1[1] + (in1[0] + 1.5707963267948966);
  t9 = -in1[4] + t8;
  a = (((-h + cos(in1[0] + 1.5707963267948966) * 0.4667) + cos(t7) * 0.4064) +
       cos(t8) * 0.4064) +
      cos(t9) * 0.4667;
  t8 = (((-k + sin(in1[0] + 1.5707963267948966) * 0.4667) + sin(t7) * 0.4064) +
        sin(t8) * 0.4064) +
       sin(t9) * 0.4667;
  return ((ub - a * a) - t8 * t8) + r * r;
}

/* End of code generation (psw_ub.c) */
