function s2 = CBF_s2(in1,in2,in3,ldes,r,m1,a)
%CBF_S2
%    S2 = CBF_S2(IN1,IN2,IN3,LDES,R,M1,A)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Nov-2020 22:05:40

c1 = in2(:,1);
c2 = in2(:,2);
c3 = in2(:,3);
c4 = in2(:,4);
c5 = in2(:,5);
qnsh = in1(4,:);
qnsk = in1(5,:);
qsf = in1(1,:);
qsh = in1(3,:);
qsk = in1(2,:);
thetamp1 = in3(:,1);
thetamp2 = in3(:,2);
t2 = a.*r;
t3 = 1.0./a;
t4 = -qnsh;
t5 = 1.0./r;
t6 = -thetamp2;
t7 = pi./2.0;
t8 = pi.*(3.0./2.0);
t9 = t2-1.0;
s2 = ldes+r-cos(qsf+qsk+t7).*(2.54e+2./6.25e+2)-cos(qsf+t7).*4.667e-1-cos(-qnsk+qsf+qsh+qsk+t4+t8).*4.667e-1-cos(qsf+qsh+qsk+t4+t8).*(2.54e+2./6.25e+2)+t9./(t2.*(exp(-m1.*((t6+c4.*qnsh+c5.*qnsk+c1.*qsf+c3.*qsh+c2.*qsk)./(t6+thetamp1)-1.0))-t9./t2))+1.0;
