function G = G_matrix(in1)
%G_MATRIX
%    G = G_MATRIX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Nov-2020 22:02:39

qnsh = in1(4,:);
qnsk = in1(5,:);
qsf = in1(1,:);
qsh = in1(3,:);
qsk = in1(2,:);
t2 = qsf+qsk;
t5 = -qnsh;
t6 = -qnsk;
t3 = qsh+t2;
t4 = sin(t2);
t7 = sin(t3);
t8 = t3+t5;
t15 = t4.*7.752247105284e+1;
t9 = sin(t8);
t10 = t6+t8;
t12 = t7.*3.63549771e+1;
t16 = -t15;
t11 = sin(t10);
t13 = -t12;
t14 = t9.*8.418717978840001;
t17 = t11.*1.436905246896;
t18 = -t17;
G = [t13+t14+t16+t17-sin(qsf).*9.7255892295144e+1;t13+t14+t16+t17;t13+t14+t17;-t14+t18;t18];
