function J_phip = J_phip(in1)
%J_PHIP
%    J_PHIP = J_PHIP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Nov-2020 22:02:40

qsf = in1(1,:);
qsk = in1(2,:);
t2 = pi./2.0;
t3 = qsf+t2;
t4 = qsk+t3;
t5 = cos(t4);
t6 = sin(t4);
t7 = t5.*(2.54e+2./6.25e+2);
t8 = t6.*(2.54e+2./6.25e+2);
t9 = -t8;
J_phip = reshape([t9-sin(t3).*4.667e-1,t7+cos(t3).*4.667e-1,t9,t7,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
