function pcm = p_cm(in1)
%P_CM
%    PCM = P_CM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Nov-2020 22:02:39

qnsh = in1(4,:);
qnsk = in1(5,:);
qsf = in1(1,:);
qsh = in1(3,:);
qsk = in1(2,:);
t2 = -qnsh;
t3 = -qnsk;
t4 = pi./2.0;
t5 = pi.*(3.0./2.0);
t6 = qsf+t4;
t9 = qsf+qsh+qsk+t2+t5;
t7 = qsk+t6;
t10 = t3+t9;
t8 = qsh+t7;
pcm = [cos(t6).*4.599051406442227e-1+cos(t7).*3.665894385550172e-1+cos(t8).*1.719159678834988e-1+cos(t9).*3.981056144498277e-2+cos(t10).*6.794859355777278e-3;sin(t6).*4.599051406442227e-1+sin(t7).*3.665894385550172e-1+sin(t8).*1.719159678834988e-1+sin(t9).*3.981056144498277e-2+sin(t10).*6.794859355777278e-3];
