function phip = p_hip(in1)
%P_HIP
%    PHIP = P_HIP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    09-Nov-2020 22:02:39

qsf = in1(1,:);
qsk = in1(2,:);
t2 = pi./2.0;
t3 = qsf+t2;
t4 = qsk+t3;
phip = [cos(t3).*4.667e-1+cos(t4).*(2.54e+2./6.25e+2);sin(t3).*4.667e-1+sin(t4).*(2.54e+2./6.25e+2)];
