/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * CBF_Lfs2.c
 *
 * Code generation for function 'CBF_Lfs2'
 *
 */

/* Include files */
#include "CBF_Lfs2.h"
#include <math.h>

/* Function Definitions */
double CBF_Lfs2(const double in1[10], const double in2[5], const double in3[2],
                double ldes, double r, double m1, double a)
{
  double t2;
  double t20;
  double t18;
  double t22;
  double t28;
  double t29;
  double t34;
  double Lfs2_tmp;
  (void)ldes;

  /* CBF_LFS2 */
  /*     LFS2 = CBF_LFS2(IN1,IN2,IN3,LDES,R,M1,A) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:01:47 */
  t2 = a * r;
  t20 = (((in1[0] + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469;
  t18 = 1.0 / (-in3[1] + in3[0]);
  t22 = (t2 - 1.0) / t2;
  t28 = sin(t20) * 0.4064;
  t29 = sin(-in1[4] + t20) * 0.4667;
  t34 = exp(-(m1 * (t18 * (((((in2[3] * in1[3] + in2[4] * in1[4]) + in2[0] *
    in1[0]) + in2[2] * in1[2]) + in2[1] * in1[1]) + -in3[1]) - 1.0)));
  t2 = t22 - t34;
  t20 = 1.0 / (t2 * t2);
  Lfs2_tmp = t28 + t29;
  t2 = (sin((in1[0] + in1[1]) + 1.5707963267948966) * 0.4064 + t28) + t29;
  return (((-in1[8] * (Lfs2_tmp + in2[3] * m1 * t18 * -t22 * t34 * t20) + in1[7]
            * (Lfs2_tmp + in2[2] * m1 * t18 * t22 * t34 * t20)) + in1[6] * (t2 +
            in2[1] * m1 * t18 * t22 * t34 * t20)) + in1[5] * ((t2 + sin(in1[0] +
             1.5707963267948966) * 0.4667) + in2[0] * m1 * t18 * t22 * t34 * t20))
    - in1[9] * (t29 + in2[4] * m1 * t18 * -t22 * t34 * t20);
}

/* End of code generation (CBF_Lfs2.c) */
