defaults:
  - module/composite_barrier: CompositeBarrier
  - module/zdyn: ZeroDynamics
  - module/yd: MLP
  - module: GeneralLearning
  - experiment
  - _self_

data_loader_workers: 0
max_epochs: 1000
batch_size: 4096
#pretrained_model: /path/to/trained/policy/model.ckpt
#pretrained_zdyn: "/path/to/trained/zero/dynamics/model.ckpt"
gpus: 1
seed: 1
dataset: OrbitalSampler
module:
  lr: 1e-2
  opt_name: 'AdamW'
  weight_decay: 1e-4
  momentum: 0.9
  decay_epochs: [50, 200, 600]
