/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Lf_t_ub.c
 *
 * Code generation for function 'Lf_t_ub'
 *
 */

/* Include files */
#include "Lf_t_ub.h"

/* Function Definitions */
double Lf_t_ub(const double in1[10], double ub)
{
  (void)ub;
  /* Lf_t_ub */
  /*     Lf_t_ub = Lf_t_ub(IN1,UB) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     04-Dec-2021 16:54:30 */
  return (-in1[5] - in1[7]) - in1[6];
}

/* End of code generation (Lf_t_ub.c) */
