/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * CBF_s2.c
 *
 * Code generation for function 'CBF_s2'
 *
 */

/* Include files */
#include "CBF_s2.h"
#include <math.h>

/* Function Definitions */
double CBF_s2(const double in1[5], const double in2[5], const double in3[2],
              double ldes, double r, double m1, double a)
{
  double t2;

  /* CBF_S2 */
  /*     S2 = CBF_S2(IN1,IN2,IN3,LDES,R,M1,A) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:01:46 */
  t2 = a * r;
  return ((((((ldes + r) - cos((in1[0] + in1[1]) + 1.5707963267948966) * 0.4064)
             - cos(in1[0] + 1.5707963267948966) * 0.4667) - cos(((((-in1[4] +
    in1[0]) + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469) * 0.4667) - cos
           ((((in1[0] + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469) *
           0.4064) + (t2 - 1.0) / (t2 * (exp(-m1 * ((((((-in3[1] + in2[3] * in1
    [3]) + in2[4] * in1[4]) + in2[0] * in1[0]) + in2[2] * in1[2]) + in2[1] *
    in1[1]) / (-in3[1] + in3[0]) - 1.0)) - (t2 - 1.0) / t2))) + 1.0;
}

/* End of code generation (CBF_s2.c) */
