defaults:
  - dyn_experiment
  - module: DynLearning
  - module/zdyn: LearnableZeroDynamics
  - module/yd: D1MLP
  - module/zdyn/epsilon: TrueMLP
  - _self_

data_loader_workers: 0
max_epochs: 2000
batch_size: 16
#pretrained_yd: /path/to/model.th
gpus: 0
seed: 1
datasets: ['RUN0',
           'RUN1',
           'RUN2']
delta_t: 10
n_steps: 3
module:
  lr: 1e-3
  opt_name: 'Nero'
  weight_decay: 1e-4
  momentum: 0.9
  decay_epochs: [50, 200]
  zdyn:
    epsilon:
      n_hidden: 128
      n_output: 2