/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * CBF_ds2edx.c
 *
 * Code generation for function 'CBF_ds2edx'
 *
 */

/* Include files */
#include "CBF_ds2edx.h"
#include "CBF_ds2edx_data.h"
#include "CBF_ds2edx_initialize.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  double d;
  double d1;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }

  return y;
}

void CBF_ds2edx(const double in1[10], const double in2[5], const double in3[2],
                double ldes, double r, double m1, double a, double ds2edx[10])
{
  double t2;
  double t13;
  double t30;
  double t24;
  double t25;
  double t26;
  double t32;
  double t33;
  double t34;
  double t27;
  double t37;
  double t42;
  double t43;
  double t44;
  double t39;
  double t40;
  double t45;
  double t47;
  double t48;
  double t56;
  double t57;
  double t59;
  double t70_tmp;
  double t91_tmp;
  double t91;
  double t92;
  double t93;
  double t95_tmp;
  double t95;
  double t96;
  double t97;
  double t98;
  (void)ldes;
  if (!isInitialized_CBF_ds2edx) {
    CBF_ds2edx_initialize();
  }

  /* CBF_DS2EDX */
  /*     DS2EDX = CBF_DS2EDX(IN1,IN2,IN3,LDES,R,M1,A) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:01:47 */
  t2 = a * r;
  t13 = m1 * m1;
  t30 = (((in1[0] + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469;
  t24 = in1[1] + (in1[0] + 1.5707963267948966);
  t25 = sin(in1[0] + 1.5707963267948966);
  t26 = 1.0 / (-in3[1] + in3[0]);
  t32 = sin(t30);
  t33 = (t2 - 1.0) / t2;
  t34 = -in1[4] + t30;
  t27 = t26 * t26;
  t2 = sin(t24);
  t37 = sin(t34);
  t42 = t32 * 0.4064;
  t43 = t32 * 32.512;
  t44 = cos(t30) * 0.4064;
  t39 = t2 * 0.4064;
  t40 = t2 * 32.512;
  t45 = t37 * 37.336;
  t47 = cos(t34) * 0.4667;
  t48 = t37 * 0.4667;
  t2 = m1 * (t26 * (((((in2[3] * in1[3] + in2[4] * in1[4]) + in2[0] * in1[0]) +
                      in2[2] * in1[2]) + in2[1] * in1[1]) + -in3[1]) - 1.0);
  t56 = exp(-t2);
  t57 = exp(-(t2 * 2.0));
  t2 = t33 - t56;
  t59 = 1.0 / (t2 * t2);
  t70_tmp = in2[3] * in2[4] * t13 * t27 * t33;
  t32 = in2[0] * in2[4] * t13 * t27 * t33;
  t91_tmp = rt_powd_snf(t2, 3.0);
  t91 = (t47 + t32 * t56 * t59) + t32 * t57 / t91_tmp * 2.0;
  t2 = in2[1] * in2[4] * t13 * t27 * t33;
  t92 = (t47 + t2 * t56 * t59) + t2 * t57 / t91_tmp * 2.0;
  t2 = in2[2] * in2[4] * t13 * t27 * t33;
  t93 = (t47 + t2 * t56 * t59) + t2 * t57 / t91_tmp * 2.0;
  t2 = in2[0] * in2[3] * t13 * t27 * t33;
  t95_tmp = t44 + t47;
  t95 = (t95_tmp + t2 * t56 * t59) + t2 * t57 / t91_tmp * 2.0;
  t2 = in2[1] * in2[3] * t13 * t27 * t33;
  t96 = (t95_tmp + t2 * t56 * t59) + t2 * t57 / t91_tmp * 2.0;
  t2 = in2[2] * in2[3] * t13 * t27 * t33;
  t97 = (t95_tmp + t2 * t56 * t59) + t2 * t57 / t91_tmp * 2.0;
  t2 = in2[0] * in2[2] * t13 * t27;
  t98 = (t95_tmp + t2 * t33 * t57 / t91_tmp * -2.0) + t2 * -t33 * t56 * t59;
  t2 = in2[1] * in2[2] * t13 * t27;
  t30 = (t95_tmp + t2 * t33 * t57 / t91_tmp * -2.0) + t2 * -t33 * t56 * t59;
  t2 = in2[0] * in2[1] * t13 * t27;
  t32 = (cos(t24) * 0.4064 + t44) + t47;
  t2 = (t32 + t2 * t33 * t57 / t91_tmp * -2.0) + t2 * -t33 * t56 * t59;
  t37 = in2[0] * in2[0] * t13 * t27;
  t44 = in2[0] * m1 * t26 * t33 * t56 * t59;
  ds2edx[0] = ((((((((t25 * 37.336 + t40) + t43) + t45) - in1[9] * t91) - in1[8]
                  * t95) + in1[7] * t98) + in1[6] * t2) + in1[5] * (((t32 + cos
    (in1[0] + 1.5707963267948966) * 0.4667) + t37 * -t33 * t56 * t59) - t37 *
    t33 * t57 / t91_tmp * 2.0)) + t44 * 80.0;
  t37 = in2[1] * in2[1] * t13 * t27;
  t24 = in2[1] * m1 * t26 * t33 * t56 * t59;
  ds2edx[1] = (((((((t40 + t43) + t45) - in1[9] * t92) - in1[8] * t96) + in1[5] *
                 t2) + in1[7] * t30) + in1[6] * ((t32 + t37 * -t33 * t56 * t59)
    - t37 * t33 * t57 / t91_tmp * 2.0)) + t24 * 80.0;
  t37 = in2[2] * in2[2] * t13 * t27;
  t34 = in2[2] * m1 * t26 * t33 * t56 * t59;
  ds2edx[2] = ((((((t43 + t45) - in1[9] * t93) - in1[8] * t97) + in1[5] * t98) +
                in1[6] * t30) + in1[7] * ((t95_tmp + t37 * -t33 * t56 * t59) -
    t37 * t33 * t57 / t91_tmp * 2.0)) + t34 * 80.0;
  t37 = in2[3] * in2[3] * t13 * t27;
  t32 = (-t47 + t70_tmp * t56 * t59) + t70_tmp * t57 / t91_tmp * 2.0;
  t30 = in2[3] * m1 * t26 * t33 * t56 * t59;
  ds2edx[3] = ((((((-t43 + -t45) - in1[5] * t95) - in1[7] * t97) - in1[6] * t96)
                - in1[9] * t32) + in1[8] * ((t95_tmp + t37 * -t33 * t56 * t59) -
    t37 * t33 * t57 / t91_tmp * 2.0)) + t30 * 80.0;
  t37 = in2[4] * in2[4] * t13 * t27 * t33;
  t2 = in2[4] * m1 * t26 * t33 * t56 * t59;
  ds2edx[4] = (((((-t45 - in1[5] * t91) - in1[7] * t93) - in1[6] * t92) - in1[8]
                * t32) - in1[9] * ((-t47 + t37 * t56 * t59) + t37 * t57 /
    t91_tmp * 2.0)) + t2 * 80.0;
  ds2edx[5] = (((t25 * 0.4667 + t39) + t42) + t48) + t44;
  ds2edx[6] = ((t39 + t42) + t48) + t24;
  ds2edx[7] = (t42 + t48) + t34;
  ds2edx[8] = (-t42 + -t48) + t30;
  ds2edx[9] = -t48 + t2;
}

/* End of code generation (CBF_ds2edx.c) */
