/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * G_matrix.c
 *
 * Code generation for function 'G_matrix'
 *
 */

/* Include files */
#include "G_matrix.h"
#include <math.h>

/* Function Definitions */
void G_matrix(const double in1[5], double G[5])
{
  double t2;
  double t3;
  double t8;
  double t14;
  double t17;

  /* G_MATRIX */
  /*     G = G_MATRIX(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:00:39 */
  t2 = in1[0] + in1[1];
  t3 = in1[2] + t2;
  t8 = t3 + -in1[3];
  t14 = sin(t8) * 8.41871797884;
  t17 = sin(-in1[4] + t8) * 1.436905246896;
  t3 = -(sin(t3) * 36.3549771) + t14;
  t8 = (t3 + -(sin(t2) * 77.52247105284)) + t17;
  G[0] = t8 - sin(in1[0]) * 97.255892295144;
  G[1] = t8;
  G[2] = t3 + t17;
  G[3] = -t14 + -t17;
  G[4] = -t17;
}

/* End of code generation (G_matrix.c) */
