/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * CBF_ds1edx.c
 *
 * Code generation for function 'CBF_ds1edx'
 *
 */

/* Include files */
#include "CBF_ds1edx.h"
#include "CBF_ds1edx_data.h"
#include "CBF_ds1edx_initialize.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  double d;
  double d1;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }

  return y;
}

void CBF_ds1edx(const double in1[10], const double in2[5], const double in3[2],
                double ldes, double r, double m1, double a, double ds1edx[10])
{
  double t2;
  double t13;
  double t30;
  double t24;
  double t25;
  double t26;
  double t32;
  double t33;
  double t34;
  double t27;
  double t37;
  double t44;
  double t45;
  double t46;
  double t39;
  double t40;
  double t49;
  double t51;
  double t52;
  double t60;
  double t61;
  double t63;
  double t73_tmp;
  double t95_tmp;
  double t95;
  double t99_tmp;
  double t99;
  double t100;
  double t101;
  double t102;
  double t103;
  double ds1edx_tmp;
  double b_ds1edx_tmp;
  (void)ldes;
  if (!isInitialized_CBF_ds1edx) {
    CBF_ds1edx_initialize();
  }

  /* CBF_DS1EDX */
  /*     DS1EDX = CBF_DS1EDX(IN1,IN2,IN3,LDES,R,M1,A) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.3. */
  /*     09-Nov-2020 22:01:34 */
  t2 = a * r;
  t13 = m1 * m1;
  t30 = (((in1[0] + in1[2]) + in1[1]) + -in1[3]) + 4.71238898038469;
  t24 = in1[1] + (in1[0] + 1.5707963267948966);
  t25 = sin(in1[0] + 1.5707963267948966);
  t26 = 1.0 / (-in3[1] + in3[0]);
  t32 = sin(t30);
  t33 = (t2 - 1.0) / t2;
  t34 = -in1[4] + t30;
  t27 = t26 * t26;
  t2 = sin(t24);
  t37 = sin(t34);
  t44 = t32 * 0.4064;
  t45 = t32 * 32.512;
  t46 = cos(t30) * 0.4064;
  t39 = t2 * 0.4064;
  t40 = t2 * 32.512;
  t49 = t37 * 37.336;
  t51 = cos(t34) * 0.4667;
  t52 = t37 * 0.4667;
  t2 = m1 * (t26 * (((((in2[3] * in1[3] + in2[4] * in1[4]) + in2[0] * in1[0]) +
                      in2[2] * in1[2]) + in2[1] * in1[1]) + -in3[1]) - 1.0);
  t60 = exp(-t2);
  t61 = exp(-(t2 * 2.0));
  t2 = t33 - t60;
  t63 = 1.0 / (t2 * t2);
  t30 = in2[0] * in2[4] * t13 * t27 * t33;
  t34 = in2[1] * in2[4] * t13 * t27 * t33;
  t73_tmp = in2[2] * in2[4] * t13 * t27 * t33;
  t32 = in2[3] * in2[4] * t13 * t27 * t33;
  t95_tmp = rt_powd_snf(t2, 3.0);
  t95 = (t51 + t32 * t60 * t63) + t32 * t61 / t95_tmp * 2.0;
  t2 = in2[0] * in2[2] * t13 * t27 * t33;
  t99_tmp = t46 + t51;
  t99 = (t99_tmp + t2 * t60 * t63) + t2 * t61 / t95_tmp * 2.0;
  t2 = in2[1] * in2[2] * t13 * t27 * t33;
  t100 = (t99_tmp + t2 * t60 * t63) + t2 * t61 / t95_tmp * 2.0;
  t2 = in2[0] * in2[3] * t13 * t27;
  t101 = (t99_tmp + t2 * t33 * t61 / t95_tmp * -2.0) + t2 * -t33 * t60 * t63;
  t2 = in2[1] * in2[3] * t13 * t27;
  t102 = (t99_tmp + t2 * t33 * t61 / t95_tmp * -2.0) + t2 * -t33 * t60 * t63;
  t2 = in2[2] * in2[3] * t13 * t27;
  t103 = (t99_tmp + t2 * t33 * t61 / t95_tmp * -2.0) + t2 * -t33 * t60 * t63;
  t2 = in2[0] * in2[1] * t13 * t27 * t33;
  t32 = (cos(t24) * 0.4064 + t46) + t51;
  t2 = (t32 + t2 * t60 * t63) + t2 * t61 / t95_tmp * 2.0;
  ds1edx_tmp = in2[0] * in2[0] * t13 * t27 * t33;
  t24 = (-t51 + t30 * t60 * t63) + t30 * t61 / t95_tmp * 2.0;
  b_ds1edx_tmp = in2[0] * m1 * t26 * t33 * t60 * t63;
  ds1edx[0] = ((((((((t25 * -37.336 + -t40) + -t45) + -t49) + in1[8] * t101) -
                  in1[7] * t99) - in1[6] * t2) - in1[9] * t24) - in1[5] * (((t32
    + cos(in1[0] + 1.5707963267948966) * 0.4667) + ds1edx_tmp * t60 * t63) +
    ds1edx_tmp * t61 / t95_tmp * 2.0)) + b_ds1edx_tmp * 80.0;
  ds1edx_tmp = in2[1] * in2[1] * t13 * t27 * t33;
  t37 = (-t51 + t34 * t60 * t63) + t34 * t61 / t95_tmp * 2.0;
  t46 = in2[1] * m1 * t26 * t33 * t60 * t63;
  ds1edx[1] = (((((((-t40 + -t45) + -t49) + in1[8] * t102) - in1[7] * t100) -
                 in1[5] * t2) - in1[6] * ((t32 + ds1edx_tmp * t60 * t63) +
    ds1edx_tmp * t61 / t95_tmp * 2.0)) - in1[9] * t37) + t46 * 80.0;
  ds1edx_tmp = in2[2] * in2[2] * t13 * t27 * t33;
  t30 = (-t51 + t73_tmp * t60 * t63) + t73_tmp * t61 / t95_tmp * 2.0;
  t34 = in2[2] * m1 * t26 * t33 * t60 * t63;
  ds1edx[2] = ((((((-t45 + -t49) + in1[8] * t103) - in1[5] * t99) - in1[6] *
                 t100) - in1[9] * t30) - in1[7] * ((t99_tmp + ds1edx_tmp * t60 *
    t63) + ds1edx_tmp * t61 / t95_tmp * 2.0)) + t34 * 80.0;
  ds1edx_tmp = in2[3] * in2[3] * t13 * t27 * t33;
  t32 = in2[3] * m1 * t26 * t33 * t60 * t63;
  ds1edx[3] = ((((((t45 + t49) - in1[9] * t95) + in1[5] * t101) + in1[7] * t103)
                + in1[6] * t102) - in1[8] * ((t99_tmp + ds1edx_tmp * t60 * t63)
    + ds1edx_tmp * t61 / t95_tmp * 2.0)) + t32 * 80.0;
  ds1edx_tmp = in2[4] * in2[4] * t13 * t27 * t33;
  t2 = in2[4] * m1 * t26 * t33 * t60 * t63;
  ds1edx[4] = (((((t49 - in1[8] * t95) - in1[9] * ((t51 + ds1edx_tmp * t60 * t63)
    + ds1edx_tmp * t61 / t95_tmp * 2.0)) - in1[5] * t24) - in1[7] * t30) - in1[6]
               * t37) + t2 * 80.0;
  ds1edx[5] = (((t25 * -0.4667 + -t39) + -t44) + -t52) + b_ds1edx_tmp;
  ds1edx[6] = ((-t39 + -t44) + -t52) + t46;
  ds1edx[7] = (-t44 + -t52) + t34;
  ds1edx[8] = (t44 + t52) + t32;
  ds1edx[9] = t52 + t2;
}

/* End of code generation (CBF_ds1edx.c) */
